### ISSUE TITLE
Nested assertions

### ISSUE THREAD

**Issue by adamralph** [dennisdoomen/FluentAssertions#118]
*from https://gist.github.com/adamralph/ac0deea6448da5a93359*

```C#
IEnumerable<Foo> foos;
 
foos.Should().All(foo => foo.Bar.Should().Be("baz"));
```
 
If an item does not satisfy the inner assertion, I'd like to be told which one.
Perhaps I could be told the index, and maybe a string representation of the item.

This is for more than just equality. I'd like to use some of the much richer assertions that FluentAssertions provides.

**Comment by dennisdoomen** [comment]
If only I could come up with a nice fluent syntax...

**Comment by Meir017** [comment]
I think this might be a bit cleaner:

````csharp
IEnumerable<People> people;
people.Should().All(person => person.Age,
                    age => age.Should().Be(21));

public static AndConstraint<GenericCollectionAssertions<T>> All<T,TProperty>(
    this GenericCollectionAssertions<T> assertions,
    Func<T, TProperty> propertySelector,
    Action<TProperty> expresstion,
    string because = "",
    params object[] becauseArgs)
{
    using (new AssertionScope())
    {
        foreach (T item in assertions.Subject)
        {
            expression((propertySelector(item));
        }
    }

    return new AndConstraint<GenericCollectionAssertions<T>>(assertions);
}
````

**Comment by dennisdoomen** [comment]
@Meir017 still doesn't feel very fluently....

**Comment by dennisdoomen** [comment]
Unless somebody can come up with a really fluent API, I don't think I can do anything with this issue.

**Comment by adamralph** [comment]
No complaints from me.

**Comment by nzkeith** [comment]
Related issue: #882
