### ISSUE TITLE
Should.Throw<TException> breaks on first chance exception

### ISSUE THREAD

**Issue by 9swampy** [dennisdoomen/FluentAssertions#152]
When I run tests expecting an exception with Should.Throw<TException> in debug mode then I would prefer the debugger not to break on the first chance exception. By definition the test is expecting the exception to be thrown so why should I have to "Continue" the test when the expected exception is thrown?

The "problem" is caused by the [DebuggerNonUserCode] attribute on the FluentAssertions.Specialized.ActionAssertions class.

For my use I've cloned and fixed fairly easily by extracting FluentAssertions.Specialized.ActionAssertions.InvokeSubjectWithInterception to a separate class that doesn't have the [DebuggerNonUserCode] attribute, but would like your thoughts on whether this behaviour change would be acceptable on the master?

Trying to be good Git [newbie] citizen I'm asking first instead of just submitting a pull request from https://github.com/9swampy/fluentassertions/commit/7a8f3fb7e7ae9cd60e6e7a7ebe32b42ad430ddae but maybe for such a small request I should have just made the request?

**Comment by 9swampy** [comment]
Updated fork https://github.com/9swampy/fluentassertions/commit/475bca3f93a44425f8af85f0949d3aa8ad8ae94a

**Comment by 9swampy** [comment]
Updated fork https://github.com/9swampy/fluentassertions/commit/695ad16e0e9224eabaaa738b8df5a9c938bf3163

**Comment by 9swampy** [comment]
That's a shame. Thanks nonetheless for all the work you put into the library.

**Comment by dennisdoomen** [comment]
You're welcome. It's just that I never managed to reproduce your problem. It currently behaves exactly as I expected it to be.
