### ISSUE TITLE
ShouldThrow also matching on subclass exception

### ISSUE THREAD

**Issue by gabrielweyer** [dennisdoomen/fluentassertions#176]
I'm not sure if it's per design or a bug.

I would expect `ShouldThrow<TException>` to only match when the exception is of the same type. Currently it will also match the sub classes.

For example if I use `ShouldThrow<ArgumentException>`, it will match if either `ArgumentNullException` or `ArgumentException` is thrown.

I created a repro case [here](https://github.com/gabrielweyer/fluentassertions-exception)

**Comment by dennisdoomen** [comment]
Fixed #181.
