### ISSUE TITLE
Unit test failing due to conversion to UTC

### ISSUE THREAD

**Issue by gabrielweyer** [dennisdoomen/fluentassertions#179]
The unit test `DateTimeOffsetValueFormatterSpecs.When_a_DateTime_is_used_it_should_format_the_same_as_a_DateTimeOffset` will throw an exception if it's ran anywhere the timezone is ahead of GMT +8.5.

When casting the DateTime `1.January(0001).At(08, 20, 01)` to a `DateTimeOffset` the code will throw an `ArgumentOutOfRangeException` in the method `DateTimeOffset.ValidateDate`. This can be fixed by ensuring that the date in UTC is after the 1st of January 0001.

**Comment by dennisdoomen** [comment]
Fixed by PR #180.
