### ISSUE TITLE
Provide reasons using lambda

### ISSUE THREAD

**Issue by paulroho** [dennisdoomen/fluentassertions#18]
Sometimes it would be handy to compose the reason message just in case of a failing assertion.
For example currently, it seems not to be possible to get a corresponding behaviour to this obviously flawed code:

```C#
customer.Should().NotBeNull("there is no matching customer, but found customer \"{0}\".", customer.FullName);
```

Suggestion (overload taking Func<T, string>):

```C#
customer.Should().NotBeNull(c => string.Format("there is no matching customer, but found customer \"{0}\".", c.FullName));
```

**Comment by dennisdoomen** [comment]
Although a nice idea, I think the amount of work will be huge.
