### ISSUE TITLE
x.Should().NotBeNull().And.Subject returns object rather than the type of x

### ISSUE THREAD

**Issue by abatishchev** [dennisdoomen/fluentassertions#198]
It turns out that `x.Should().NotBeNull().And` returns `ObjectAssertions` having its `Subject` of type `object` rather than of `x`. So you can't nest assertions.

```csharp
Foo foo = new Foo();
AndConstraint<ObjectAssertions> c = foo.Should().NotBeNull();
ObjectAssertions a = c.And;
object s = a.Subject; // here I'd expect Foo
```

 How can it be enhanced?

**Comment by bkoelman** [comment]
In case you want to prevent "possible NullReferenceException" warnings, [this](https://stackoverflow.com/questions/9841855/any-way-to-ignore-possible-null-reference-exception-warnings-when-using-assert-s#answer-36516790) may help.

Example usage:
```csharp
// Assert
Customer firstCustomer = customers[0].ShouldNotBeNull();
firstCustomer.Name.Should().Be("John Doe");
```
