### ISSUE TITLE
Access to Subject without And

### ISSUE THREAD

**Issue by adamralph** [dennisdoomen/fluentassertions#200]
At the moment I'm doing the following in order to squash a type assertion and assignment into an expression for xBehave.net:

```C#
"And the event should indicate that a widget has been added"
   .f(() => widgetAdded = (WidgetAdded)@event.Should().BeAssignableTo<WidgetAdded>().And.Subject);
```

The `And.Subject` is really odd when you read that back. I've no idea if it's feasible but, in cases such as this, it would be nice to have the option to drop the conjunction `And`:

```C#
"And the event should indicate that a widget has been added"
   .f(() => widgetAdded = (WidgetAdded)@event.Should().BeAssignableTo<WidgetAdded>().Subject);
```

Of course I could just drop the assertion and just cast only, but then if the test were to fail I'd have a nasty `InvalidCastException` in my test output instead of a lovingly crafted FluentAssertions exception.

I guess even nicer would be if `BeAssignableTo()` already casts `Subject` to the asserted type, removing the need for me to cast:

```C#
"And the event should indicate that a widget has been added"
   .f(() => widgetAdded = @event.Should().BeAssignableTo<WidgetAdded>().Subject);
```

Even if dropping the need for `And` is not possible, it would be great if this casting could happen. I'd be happy to raise a separate issue for that if you think it's feasible.

**Comment by dennisdoomen** [comment]
@adamralph, you still think this is a wise idea?

**Comment by adamralph** [comment]
I think so, yes. I'm wondering if it may be worth deprecating `Which` in favour of `Subject`?

**Comment by dennisdoomen** [comment]
That'll break the fluent API I introduced in 3.2.

**Comment by adamralph** [comment]
I'm only suggesting a deprecation, not a removal. I.e. `[Obsolete]`.

Although, that's not really necessary, you could just have `Subject` as a synonym for `Which`, doing exactly the same thing.

**Comment by adamralph** [comment]
:+1:
