### ISSUE TITLE
Using(IEquivalencyStep) executes steps in reverse order

### ISSUE THREAD

**Issue by vossad01** [dennisdoomen/fluentassertions#205]
This is currently an unreleased feature which I added to be behave the same as Using(IAssertionRule), but I am not sure the behavior is intuitive.

Right now if I do:

``` c#
opts => opts.Using(new DomainTypesEquivalencyStep()).Using(new AllObjectsStep())
```

where `AllObjectsStep` handles everything, the custom domain handling step would never be hit.  It seems odd to me that execution would not would follow left-to-right according to the registrations.

I am guessing there was a reason IAssertionRule was was done this way, but I am not sure what it was or whether it is applicable.  It may have something to do with `Using<TProperty>(Action<IAssertionContext<TProperty>> action)`

[Relevant line](https://github.com/dennisdoomen/fluentassertions/blob/5aeeb3062c8c2d008a584ddff2ed31f720a0b5b7/FluentAssertions.Core/Equivalency/EquivalencyAssertionOptionsBase.cs#L443).  Changing would take a little care because some methods that call through there would still need to prepend to preserve released behavior.

**Comment by dennisdoomen** [comment]
I'm pretty sure I never really thought about this and (maybe naively) assumed this would not be used heavily, let alone used with more than one custom `IAssertionRule`
