### ISSUE TITLE
TimeSpanValueFormatter throws on OverflowException when its value contains TimeSpan.MinValue

### ISSUE THREAD

**Issue by splintor** [dennisdoomen/fluentassertions#212]
When an assertion fails, and its object contains a TimeSpan field which has a value of TimeSpan.MinValue, an OverflowException is thrown.
This is because TimeSpanValueFormatter.ToString() calls TimeSpanValueFormatter.GetNonZeroFragments(), which calls timeSpan.Duration(), which throws OverflowException exception if its Ticks equals to TimeSpan.MinValue.Ticks.

**Comment by dennisdoomen** [comment]
Thanks for reporting that.
