### ISSUE TITLE
Adding StyleCop

### ISSUE THREAD

**Issue by konstmsu** [dennisdoomen/fluentassertions#213]
What do you think if we add StyleCop to validate coding guidelines? It can detect missing brackets forcing

    if (a) B();

and

    if (a)
        B();

to be

    if (a)
    {
        B();
    }

Unfortunately if we enforce this rule then they will have to be added to lines like this:

    if (considered.Contains(subInterface)) continue;

and

    if (ReferenceEquals(null, obj)) return false;
    if (ReferenceEquals(this, obj)) return true;
    if (obj.GetType() != this.GetType()) return false;

There are 7 lines like these that would need changing but the whole codebase will be checked for consistency.

**Comment by dennisdoomen** [comment]
ReSharper can do this as well, provided that we add the correct solution-wide settings to the repository?

**Comment by vossad01** [comment]
@konstmsu In this case would StyleCop be enforcing the policy on build?  Or itself formatting the code?

I know it can do the former but I am not sure about the latter.  I use StyleCop as a ReSharper plug-in so that ReSharper can better show/respect StyleCop rules, but I have never tried using StyleCop standalone before.

**Comment by konstmsu** [comment]
I _think_ github can run StyleCop when the code is pushed so you will have
less style issues during code reviews.
Also I've added StyleCop on my local fluentassertions build and it revealed
quite a number of formatting inconsistencies and grammar mistakes in
comments so even if you are currently using ReSharper, StyleCop is more
comprehensive.

**Comment by konstmsu** [comment]
@vossad01 Answering your question, StyleCop will be enforcing the policy on build so there will be required less effort on code review.

**Comment by vossad01** [comment]
Sounds like a good thing to me.

StyleCop is configurable on what rules are enforced?  I know the R# extension wanted Copyright headers at the top of all files and other things we might not want.

**Comment by konstmsu** [comment]
Every rule is configurable, I've got a rule set that passes on the current
fluent assertions codebase with some minor fixes.
I'll send another pull request after we finish with the current one.

**Comment by dennisdoomen** [comment]
Cool. Could you make it part of the build script? Then it'll get included in the TeamCity builds.

**Comment by 9swampy** [comment]
If you'd be happy to take a nuget dependency https://www.nuget.org/packages/StyleCop.MSBuild would achieve all that's been suggested. We use it in all our builds, works seemlessly on local builds as well as on the TC build agents.

**Comment by vossad01** [comment]
Resolved by #216
