### ISSUE TITLE
ShouldBeEquivalentTo does not compare fields.

### ISSUE THREAD

**Issue by TorbenRahbekKoch** [dennisdoomen/fluentassertions#22]
It works fine on properties, but public fields are not taken into account. One can discuss whether this is a good thing or not, though ;)

Thanks for a very nice fluent api, with very few surprises.

**Comment by vossad01** [comment]
Anyone care to weigh in on the behavior of this edge case?

``` c#
[TestMethod]
public void When_asserting_equivalence_including_only_fields_it_should_not_match_properties()
{
	//-----------------------------------------------------------------------------------------------------------
	// Arrange
	//-----------------------------------------------------------------------------------------------------------
	var onlyAField = new ClassWithOnlyAField { Value = 1 };
	var onlyAProperty = new ClassWithOnlyAProperty { Value = 1 };

	//-----------------------------------------------------------------------------------------------------------
	// Act
	//-----------------------------------------------------------------------------------------------------------
	Action act = () => onlyAField.ShouldBeEquivalentTo(
            onlyAProperty,
            opts => opts.IncludingAllDeclaredFields());

	//-----------------------------------------------------------------------------------------------------------
	// Assert
	//-----------------------------------------------------------------------------------------------------------
	???
}
```

My initial inclination is that it should fail because the matching member on the expectation object is a   property and we specified to only include fields.

However, we do not respect the Runtime/Declared distinction on the expectation object, so perhaps we should not be respecting the Property/Field distinction either.

**Comment by dennisdoomen** [comment]
It should fail. Fields and properties are fundamentally different things and should not be confused with the Runtime/Declared distinction which is more about visibility.

**Comment by dennisdoomen** [comment]
This was already completed in release 3.3.0.
