### ISSUE TITLE
Deadlock in WinRT when [UITestMethod] fails

### ISSUE THREAD

**Issue by kozw** [dennisdoomen/fluentassertions#223]
A WinStore 8.1 unit test library with a test method decorated with [UITestMethod] will dead lock when the test fails. The lock occurs in FluentAssertions.Execution.GetAssemblies where the async GetAssemblyListAsync method task is blocked by querying its Result.

The lock only occurs when the TestFrameworkProvider has not been initialized yet. That is also my workaround for now; adding a test method (decorated with [TestMethod]) that always fails and is executed before any ui test methods are, so the TestFrameworkProvider is initialized. 

This issue also occurs in WP81 with a custom UITestMethodAttribute implementation (attribute doesn't exist yet for WP81).

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Would it be possible to provide some kind of example solution? I don't even know where to start to reproduce this.

**Comment by kozw** [comment]
No problem;

Create a new Windows Store 8.1 Unit Test Library and replace UnitTest1.TestMethod1 with the following

```c#
[UITestMethod]
public void TestMethod1()
{
    0.Should().Be(1);
}
```
```UITestMethodAttribute``` is in namespace ```Microsoft.VisualStudio.TestPlatform.UnitTestFramework.AppContainer```

Run this single test in the Test Explorer and the run will never stop. When debugging FluentAssertions, you'll notice that a deadlock occurs in FluentAssertions.Execution.GetAssemblies 

IMHO the easiest solution is to initialize the TestFrameworkProvider before executing any test method.

**Comment by dennisdoomen** [comment]
Thanks. I'll try to reproduce it with that.
