### ISSUE TITLE
Xamarin iOS Unified API

### ISSUE THREAD

**Issue by Planverlust** [dennisdoomen/fluentassertions#231]
I migrated a test project on Xamarin iOS to new Unified API.
Now the compiler doesn't find the "Should"...-Extensions any more. ("Type XXX does not contain a definition for `Should' and no extension method `Should' of type XXX could be found. Are you missing an assembly reference?")

checked: using FluentAssertions;
checked: Nuget Package FluentAssertions and FluentAssertions.Xamarin, both say Version 3.2.2, Target Framework is Xamarin.IOS, Version=v1.0
checked: References/From Packages: Both FluentAssertions.Core.dll and FluentAssertions.dll are referenced

I have some tests with classic Assertions too. The rest of the test project compiles fine, if i uncomment the FluentAssertions-Lines.

**Comment by vossad01** [comment]
@onovotny may be able to shed some light on this.

**Comment by dennisdoomen** [comment]
@onovotny, is this still an issue?

**Comment by onovotny** [comment]
I haven't been able to repro. Can you try again with the latest version? I just released the FluentAssertions.Xamarin 3.4.0 to match the main 3.4 release.

**Comment by Planverlust** [comment]
Sorry for the delay,
yes, this is still an issue for me. I've updated my packages and still no Should().
I can reproduce this by making a simple new test project for Xamarin iOS and add the Fluent Assertions for Xamarin package. it's here: https://dl.dropboxusercontent.com/u/2395336/FATestTest.zip
Perhaps i'm doing something fundamentally wrong? Can't imagine what...
On Windows, i'm a regular user of FluentAssertions and i can't live without it!

**Comment by onovotny** [comment]
Hmm...looks like an error with the ios unified profile; fixing now.

**Comment by onovotny** [comment]
Can you try FluentAssertions.Xamarin 3.4.1? That should have the fix.

**Comment by Planverlust** [comment]
Yes, works great :-). Thank you very much!
I'm happy to use FluentAssertions for my Xamarin projects now!

**Comment by dennisdoomen** [comment]
Much appreciated @onovotny!
