### ISSUE TITLE
TargetInvocationException on ShouldAllBeEquivalentTo when class has IReadOnlyList property and its null

### ISSUE THREAD

**Issue by MichaelLogutov** [dennisdoomen/fluentassertions#233]
The test (in [fiddler](https://dotnetfiddle.net/v6PsTb)):

	public class MyClass
	{
		public IReadOnlyList<string> Items
		{
			get;
			set;
		}
	}

	public static void Main()
	{
		new[]
		{
			new MyClass { Items = new[] { "a" } }
		}
		.ShouldAllBeEquivalentTo(new[]
		{
		 new MyClass()
		});
	}

**Comment by vossad01** [comment]
Thanks Michael.  The fiddler does not load for me so I cannot see what version of FA you are using.  However, I just tested this against 3.3.0 which I expect will released soon and did not recreate your issue, so I believe this has been addressed.

It gives the following failure message:

> Item[0].Items is a collection and cannot be compared to <null>.

**Comment by MichaelLogutov** [comment]
Yeah, fiddler is down currently.
Anyway, I think the message is better than exception but still it's not correct equivalency result - the null for enumerables should be the same as getting empty enumerable if compared to non null value.

**Comment by vossad01** [comment]
Was that behavior exhibited by a previous version of FA?  I am not familiar with it treating null as empty.

**Comment by MichaelLogutov** [comment]
Well, it should something like "expected collection of 1 item but found null".

**Comment by vossad01** [comment]
Ahh, just noticed GitHub clipped the message because I did not escape the angle brackets.

> Item[0].Items is a collection and cannot be compared to \<null\>.

So the request is to enumerate the collection to get a count when comparing to null?

If you want 'null as empty' behavior, I believe (in 3.3.0) you could write a custom IEquivalencyStep to do the replacement.  It would be similar to `TryConversionEquivalencyStep`.

**Comment by dennisdoomen** [comment]
FA would never treat a `null` as empty because that would go against the principles of the .NET framework.

**Comment by MichaelLogutov** [comment]
Guys, when someone calls ShouldAllBeEquivalentTo to compare two arrays of the objects of the same classes he's not expecting to get "I can not compare those values, sorry" don't you think? The example is perfectly fine as it is - FA should said that those arrays are different because expected object has property "Item" not null and target item has this property set to null.

**Comment by dennisdoomen** [comment]
Yeah, I see your point. I'll fix the message.

**Comment by dennisdoomen** [comment]
Fixed
