### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by Fydon** [dennisdoomen/fluentassertions#235]
Is there a way to get the object inside a interface to be compared, without explicitly typecasting? In the example below I need to know to iterate through a list to check equivalence, as the first check only checks the list and not the properties of class c.

    interface i
    {
    }

    class c : i
    {
        public string property { get; set; }
    }

    class Program
    {
        static void Main( string[] args )
        {
            var a = new List<i> { new c() { property = "hello" } };
            var b = new List<i> { new c() { property = "world" } };

            a.ShouldBeEquivalentTo( b );
            for( int i = 0; i < a.Count; ++i )
            {
                ( (c)a[i] ).ShouldBeEquivalentTo( (c)b[i] ); // AssertionFailedException thrown here
            }
        }
    }

**Comment by dennisdoomen** [comment]
Thank you for reporting this. I'm pretty sure you need to specify the option 'IncludingAllRuntimeProperties'. By default FA is supposed to look at the declared type only (which is `i` in this case) and since `i` doesn't have any properties, it won't look at them.

**Comment by vossad01** [comment]
Alternatively, now that 3.3.0 has released, you can use the `RespectingRuntimeTypes` option.

```c#
a.ShouldBeEquivalentTo(b, options => options.RespectingRuntimeTypes());
```

You can even configure that to be the default behavior using the static `AssertionOptions` class, if appropriate.

**Comment by Fydon** [comment]
Thank you. Both solutions worked fine.
