### ISSUE TITLE
Using the because string parameter

### ISSUE THREAD

**Issue by Meir017** [dennisdoomen/fluentassertions#237]
````csharp
[TestMethod]
public void ItemsCount()
{
    int items = 5;
    int expected = 3;
    items.Should().Be(expected, "because number of items is incorrect.");
}
````
This way the error message I get is "Expected 3 because number of items is incorrect, but found 5."
I want the error message to be  "Expected 3 but found 5, because number of items is incorrect."
I there any way to do this?
I found I way around this:
````csharp
[TestMethod]
public void ItemsCount()
{
    int items = 5;
    int expected = 3;
    items.Should().Be(expected, "because number of items should be {0}, expected);
}
````
But it doesn't seem right to me.
Any ideas?

**Comment by vossad01** [comment]
See [this StackOverflow post](http://stackoverflow.com/a/23965946/1072626) for example and explanation of how `because` is used.

**Comment by Meir017** [comment]
Thanks, I was used to the error messages from MsTest...
