### ISSUE TITLE
ArgumentOutOfRangeException when comparing DateTime.MaxValue or DateTime.MinValue with BeCloseTo()

### ISSUE THREAD

**Issue by Sandra121289** [dennisdoomen/fluentassertions#241]
Hi,

yesterday I found this bug:

`DateTime.MaxValue.Should().BeCloseTo(DateTime.MaxValue);`

throws `System.ArgumentOutOfRangeException`. Same goes for `DateTime.MinValue`.

For now I use a custom compare method to work around the issue.

**Comment by dennisdoomen** [comment]
Hi @Sandra121289, thanks for reporting this. Which version of FA have you been using?

**Comment by Sandra121289** [comment]
Hi @dennisdoomen ,

we are using Version 3.2.2 with .NET 4.0.

**Comment by Sandra121289** [comment]
just updated the nuget-Package to version 3.3.0, bug stays.

**Comment by dennisdoomen** [comment]
Hmm, I suppose this is just an example, isn't it? You're not actually comparing `DateTime.MaxValue` with itself?

**Comment by Sandra121289** [comment]
Well, yes and no. This is of course a simplified example. At some point in our software DateTime.MaxValue is representing infinity, so we compare some objects in the unit tests, that have these values.

**Comment by vossad01** [comment]
I can confirm the given example fails for me.  If it is failing for you, it is probably another time zone dependent issue.

I wonder if @konstmsu was still thinking about working on `DateTime` and `DateTimeOffset` handling?

**Comment by dennisdoomen** [comment]
Tonight, I was trying to fix this, but I'm afraid we're running out of options to work around all those implicit `DateTime` to `DateTimeOffset` conversions. I'm afraid we really need to start separating them.

**Comment by dennisdoomen** [comment]
Will be part of release 3.4, but if you want to verify the fix, you can get pre-release package `FluentAssertions 3.4.0-unstable0004` or later from the MyGet feed here: https://www.myget.org/F/fluentassertions_ci/
