### ISSUE TITLE
Enhancement: Overload CollectionAssertions.OnlyHaveUniqueItems() with IEqualityComparer

### ISSUE THREAD

**Issue by jrnail23** [dennisdoomen/fluentassertions#255]
Just ran into a case where I want to assert that all of the objects have identical values for all properties EXCEPT one in particular.  So my collection items should all be unique, but *almost* the same.  
Throwing in an IEqualityComparer seems like an easy way to facilitate this...

Any other ideas on how I might compose this kind of assertion?

**Comment by dennisdoomen** [comment]
Why not use `collection.ShouldAllBeEquivalentTo(otherCollection, options => options.Excluding(x => x.SomeProperty)`?

**Comment by jrnail23** [comment]
Yeah, that's obviously much better -- must've missed those options before.  Thanks!
