### ISSUE TITLE
Assertions to verify assembly and type structure

### ISSUE THREAD

**Issue by piotrpMSFT** [dennisdoomen/fluentassertions#271]
I would like to expand the capabilities of the existing reflection assertions [Assembly, Type, MethodInfo, PropertyInfo] and add a few related assertions [ConstructorInfo, MemberInfo, MethodBase] to enable reasoning about the structure of assemblies and the types they contain.

**AssemblyAssertions**
AssemblyAssertions should expose the ability to assert that an assembly exposes a particular type:

```csharp
this.GetType().Assembly
    .Should().DefineType("MyNamespace", "MyTestClass")
         .Which.Should().BeDecoratedWith<TestClassAttribute>();
```

**TypeAssertions**
TypeAssertions should allow us to assert that the type has expected members, does not have other members, is derived from a base class, and implements some interfaces:

```csharp
typeof(MyClass)
    .Should().Implement(typeof(IEnumerable), "Because I like those linq extension methods")
       .And.Implement<IEnumerable>("Because this syntax is often more convenient!")
       .And.NotImplement(typeof(IOrderedEnumerable), "Because I intentionally don't guarantee order")
       .And.NotImplement<IOrderedEnumerable>("Because this syntax is often more convenient!")
       .And.BeDerivedFrom(typeof(MyBaseClass), "Because I'm a specialization of that class")
       .And.BeDerivedFrom<MyBaseClass>("Because this syntax is often more convenient!")
       .And.HaveIndexer(new [] { typeof(int) }, "Because I'm a collection of some sort")
       .And.NotHaveIndexer(new [] { typeof(string) }, "Because that would be inefficient")
       .And.HaveProperty(typeof(string), "MyStringProperty", "Because my users expect it")
       .And.HaveProperty<string>("MyStringProperty", "Because this syntax is often more convenient!")
       .And.NotHaveProperty(typeof(string), "YourStringProperty", "Because it belongs on a different class")
       .And.NotHaveProperty<string>("YourStringProperty", "Because this syntax is often more convenient!")
       .And.HaveMethod("Jump", new [] { typeof(long) }, "Because how high?")
       .And.NotHaveMethod("Jump", new [] { typeof(string) }, "Because AtoI is not our concern here")
       .And.HaveExplicitProperty(typeof(IHaveAName), "Name", "Because properties are sometimes implemented explicitly to avoid name collisions")
       .And.HaveExplicitProperty<IHaveAName>("Name", "Because this syntax is often more convenient!")
       .And.NotHaveExplicitProperty(typeof(IHaveAName), "LastName", "Because this property should have a unified implicit/explicit implementation")
       .And.NotHaveExplicitProperty<IHaveAName>("LastName", "Because this syntax is often more convenient!")
       .And.HaveExplicitMethod(typeof(ICanJump), "Jump", new [] { typeof(long) })
       .And.HaveExplicitMethod<ICanJump>("Jump", new [] { typeof(long) }, "Because this syntax is often more convenient!")
       .And.NotHaveExplicitMethod(typeof(ICanJump), "Jump", new [] { typeof(string) })
       .And.NotHaveExplicitMethod<ICanJump>("Jump", new [] { typeof(string) }, "Because this syntax is often more convenient!")
       .And.HaveConstructor(new [] { typeof(IMyRepository) }, "Because it allows dependency injection")
       .And.HaveDefaultConstructor("Because I want to verify...")
           Which.Should().HaveAccessModifier(CSharpAccessModifiers.Private, "Because I don't want to be created without a repository!");
```

**MethodBaseAssertions**
By exposing MethodBaseAssertions seperately from MethodInfo we can share code that applies to other implementations of MethodBase like ConstructorInfo.

```csharp
myMethodBase
    .Should().Return(typeof(int), "Because that's this overload's job")
       .And.Return<int>("Because this syntax is often more convenient!")
       .And.ReturnVoid("Because contradictions are fun")
       .And.HaveAccessModifier(CSharpAccessModifier.Internal);
```

**MethodInfoAssertions**
These retain their previous characteristics but can now also check for Async!
```csharp
myMethodInfo
    .Should().BeAsync("Because it's long running.");
```

**PropertyInfoAssertions**
These are analagous to what we can do with Methods.
```csharp
myPropertyInfo
    .Should().BeWritable("Because it should have a setter, though I don't care about its accessability")
       .And.BeWritable(CSharpAccessModifier.ProtectedInternal, "Because I do care")
       .And.BeReadable()
       .And.BeReadable(CSharpAccessModifier.Public)
       .And.NotBeReadable()
       .And.NotBeWritable()
       .And.Return(typeof(MyReturnType))
       .And.Return<MyReturnType>("Because this syntax is often more convenient!")
```

I am preparing a PullRequest to add these capabilities to the FluentAssertions project and am creating this issue to request approval for adding these capabilities and to have a discussion around the shape of the new assertions. I want to make sure this makes sense to the project overall before asking folks to review code.

**Comment by dennisdoomen** [comment]
Awesome. Those would be a valuable addition to FA. And you can use those examples for the documentation section as well.

**Comment by piotrpMSFT** [comment]
Notice that many of these assertions take parameters of type Type. Do FA consumers expect Type parameters to provide <Tin> overloads. For example:

```csharp
propertyInfo.Should().Return(typeof(string))

versus

propertyInfo.Should().Return<string>();

```

The first implementation was important for our scenarios since we used this to validate code generation tooling and therefore the Type was not known at design-time. However, I wonder if the second wouldn't be more natural for FA in general. What do you think?

**Comment by dennisdoomen** [comment]
Usually I provide both options.

**Comment by piotrpMSFT** [comment]
Do you have a favorite example? The overloads are trivial, but I want to be consistent with the rest of the project regarding how much testing goes into validating them. My knee-jerk opinion is to provide full testing on one and then happy-path validation for the other. Does that match the intent of the project?

**Comment by dennisdoomen** [comment]
In most cases where I had to deal with that, the generic version will call the non-generic version. So from that perspective I would say your approach is fine.
