### ISSUE TITLE
Provide Nullness guarantees as attributes or external annotations

### ISSUE THREAD

**Issue by arlobelshee** [dennisdoomen/FluentAssertions#272]
I generally use ReSharper's Null checking at the highest level. This lets me avoid any NREs. However, it requires that all instances of an object reference (param, field, return value) indicate nullness guarantee.

I love FluentAssertions, but it doesn't indicate any nullness contracts. Which means I typically have to supply external annotations files. That becomes a pain with multiple projects, multiple machines to config, etc.

In the case of FuentAssertions, the main contract declaration that would be useful is [NotNull] on the return value of all the chaining methods. Secondary value would be [NotNull] or [CanBeNull] on parameter declarations for the extension methods.

It would be a lot simpler for me if the library included these contracts out of the box - via either Attributes (which requires taking a dependency on a R# NuGet package) or external annotations (which requires keeping an XML file up to date as things change). I generally find the attributes superior as ReSharper will remind me to keep them up to date and they are right next to the code they describe, but I recognize that some library authors are wary of adding dependencies.

Would you accept a PR that specified contracts for your public API? Would you maintain it in subsequent releases? If so, which way would you prefer - attributes or external annotations?

**Comment by dennisdoomen** [comment]
After a [short discussion](https://gitter.im/dennisdoomen/fluentassertions?at=557e8fe97d5adaae3b4f116f), absolutely, provided that you'll use the internalized attributes so that we don't get a dependency on some kind of external NuGet package

**Comment by dennisdoomen** [comment]
@arlobelshee You're still on this?

**Comment by vansha** [comment]
+1
I may work on pull request

**Comment by vansha** [comment]
Sorry, I've misread the issue description. What I was thinking about is to annotate assertion methods with ```ContractAnnotations``` attribute, so that Resharper knows the result of an assertion check and can provide suggestions based on that checks. Below is an example for assertions made as extension methods.
![image](https://cloud.githubusercontent.com/assets/147127/10122798/29ec3f4a-652d-11e5-8bf5-ccae46ab4914.png)

But unfortunately it seems that such approach won't work with fluentassertions. Because assertion methods are implemented as instance methods which don't have subject value as a method parameter. (See [BooleanAssertion](https://github.com/dennisdoomen/fluentassertions/blob/develop/Src/Core/Primitives/BooleanAssertions.cs#L33) example). As far as I understand this is not supported by ```ContractAnnotations```.

Without suggestions based on annotated assertion methods, this issue becomes not that important for me.

**Comment by jotabe-net** [comment]
I have just started using `FluentAssertions`, so I don't know it with enough depth, but wouldn't something like this work?
```C#
[ContractAnnotation("notnull => halt")]
public static AndConstraint<ObjectAssertions> ShouldBeNull(this object actualValue)
{
    return actualValue.Should().BeNull();
}
```

**Comment by smad2005** [comment]
I think it's still actual.

All `Should()` methods marked by resharper (pessimistic mode) as "possible NRE"

- https://www.jetbrains.com/help/resharper/2017.1/Code_Analysis__External_Annotations.html
- https://youtrack.jetbrains.com/issue/RSRP-453476 (annotations generator)

**Comment by Bulan** [comment]
@dennisdoomen I think this should be reopened.

Resharper still doesnt understand FluentAssertions null check:

![resharper_fluentassert_nullcheck](https://cloud.githubusercontent.com/assets/311684/25171853/7dcefd9a-24ef-11e7-8b58-281fad5012a3.png)

From quickreading this:
https://blog.jetbrains.com/dotnet/2010/11/17/resharper-nullreferenceexception-analysis-and-its-contracts/

And looking at #499,

My guess is that `[NotNull]` annotation (contract) should be added to `NotBeNull ` method of FluentAssertions 
(and of course if there are any other methods asserting null)

**Comment by arlobelshee** [comment]
For that one case to work, it would have to be on ex.InnerException. But ex.InnerException could possibly be null; R# is correct. TO get the computed case that you are thinking, you’d have to use a custom contract assertion.

I don’t remember the details, but there’s one like “DoesNotReturnIf,” which you then provide with “ArgumentIsNull.” And you’d apply that to NotBeNull.

Of course, the even better way is to use Fluent Assertions’ `ex.Should().HaveInnerException().` (or whatever that one was called).

Arlo
