### ISSUE TITLE
ShouldBeEquivalentTo() crashes with StackOverflowException on nulls

### ISSUE THREAD

**Issue by murgo** [dennisdoomen/fluentassertions#280]
Using the latest FluentAssertions 3.4.0 from Nuget.

If ShouldBeEquivalentTo() is used on a null object, test goes into infinite loop throwing a StackOverflowException, crashing the whole test runner.
```C#
        [TestMethod]
        [TestCategory("Unit")]
        public void ShouldBeEquivalentTo_NullValue_ProbablyShouldntCrashTheWholeTestRunner()
        {
            ((object)null).ShouldBeEquivalentTo("foo"); // crash and burn
        }
```

This worked fine in 3.3.0.

**Comment by dennisdoomen** [comment]
Thanks for reporting that. I'll investigate that tonight.

**Comment by dennisdoomen** [comment]
Fixed in https://www.nuget.org/packages/FluentAssertions/3.4.1
