### ISSUE TITLE
Nuget package for CoreFx 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [dennisdoomen/fluentassertions#283]
We would like to use FluentAssertions in CoreFxLab (https://github.com/dotnet/corefxlab) and possibly in CoreFx. Unfortunately, the FluentAssertions Nuget package does not support CoreFx contracts and versions, i.e. portable+win81+wpa8 has a hard dependency on Windows Runtime, and other targets are fold older platforms.

**Comment by onovotny** [comment]
:+1:

I can help with this impl.

**Comment by dennisdoomen** [comment]
Isn't that related to https://github.com/dennisdoomen/fluentassertions/issues/265?

**Comment by dennisdoomen** [comment]
Solved by #288
