### ISSUE TITLE
Omnisharp: You must add a reference to assembly 'mscorlib'

### ISSUE THREAD

**Issue by koenmetsu** [dennisdoomen/fluentassertions#284]
I'm getting the following error when building with the latest omnisharp (atom).

Any idea?

![2015-07-08_1447](https://cloud.githubusercontent.com/assets/1169539/8570414/5823ee54-2580-11e5-8ff7-4840d4d49ce8.png)

**Comment by dennisdoomen** [comment]
What version of FA are you using? And what platform are you using in that project?

**Comment by koenmetsu** [comment]
Issue occurs on 3.3.0 and 3.4.1, to which I just upgraded.

Class library project, .NET Framework 4.5, on a Win 7 Enterprise 64bit.
Atom 1.0, Omnisharp 0.17.3.

NB: works fine in VS2013.

**Comment by dennisdoomen** [comment]
Sounds like a problem with Omnisharp not having the correct stuff installed for working with Portable Class Libraries. Might [this post](https://github.com/OmniSharp/omnisharp-server/issues/192) be a solution?

**Comment by koenmetsu** [comment]
I've been having the same issue with other packages as well after creating this issue here, so I'll close this one and add it with omnisharp. Thanks!

**Comment by dennisdoomen** [comment]
OK, no problem.
