### ISSUE TITLE
Enhancement: Allow BeEquivalentTo to take an equality comparer for the collection items

### ISSUE THREAD

**Issue by somewhatabstract** [dennisdoomen/FluentAssertions#286]
There are situations where it would be really handy to be able to pass an `IEqualityComparer` instance to `BeEquivalentTo` for comparing collection elements. Something like:

```
IEnumerable<MyObject> result = GetResults();

result.Should().BeEquivalentTo( expectation, MyObjectComparer.Default );
```

**Comment by dennisdoomen** [comment]
Sure. I'd love to get a Pull Request for that.

**Comment by somewhatabstract** [comment]
I was wondering about that but I didn't want to be all "hey, here's some code" in case there was a good reason why it didn't already do this. I'll see if I can make it happen.

**Comment by dennisdoomen** [comment]
@somewhatabstract any progress?

**Comment by somewhatabstract** [comment]
I took a look at it, but got overwhelmed with other tasks. So far, I was struggling to work out how the architecture fit together to make an idiomatic change. Didn't want to hack it in there. It's an impressive code base and I admit to getting a little lost.

**Comment by somewhatabstract** [comment]
That said, I was able to meet most of my concerns using options to exclude properties and such.
