### ISSUE TITLE
Short and easy Decimal asserts (alt. for BeApproximately)

### ISSUE THREAD

**Issue by stigc** [dennisdoomen/fluentassertions#289]
Couldn't we add a feature ShouldRoundTo so we could do

            value.ShouldRoundTo(0.5952m);

instead of 

            value.BeApproximately(0.5952m, 0.001m);

(warning, untested code! ToString is for sure not the right solution)

        public static void ShouldRoundTo(this decimal @this, decimal that)
        {
            int digitsAfterSeperator = BitConverter.GetBytes(decimal.GetBits(that)[3])[2];

            var roundedValue =  Math.Round(@this, digitsAfterSeperator);

            if (!roundedValue.ToString().StartsWith(that.ToString()))
                Assert.Fail("Rounded value of " + @this + " does not start with " + that);
        }

**Comment by stigc** [comment]
Hi again, I used a extension for month and it is not at very good idea. You forget to add trailing zeros when asserting figures like 1 or 0 and you end up with a lots of trailing zeros.

**Comment by dennisdoomen** [comment]
So? Should I close this issue?
