### ISSUE TITLE
FluentAssertion.Core dll is using mscorelib 2.0.5.0 for .NET 4.0 or 4.5

### ISSUE THREAD

**Issue by oolaru** [dennisdoomen/fluentassertions#294]
Visual Studio 2013, a .NET 4.0 or 4.5 application - I am trying to update the nuget package version of FluentAssertions from 2.2.0 to any version > 3.3.  I am using Package Manager Console from VS for update.
It ads a new referrnce to FluentAssertions.Core.dll - this is correct.

The issue: Any FluentAssertions.Core.dll from the package is using mscorelib 2.0.5 instead of mscorelib 4.0 (see attached)

![image](https://cloud.githubusercontent.com/assets/14071392/9601219/c694e1f6-50a8-11e5-9f64-c841f2f932c8.png)

This issue needs to be fixed.

**Comment by dennisdoomen** [comment]
Hi @oolaru. `FluentAssertions.Core` is a portable class library so it should reference 2.0.5.0 of `mscorlib`.

**Comment by oolaru** [comment]
it makes sense. thanks a lot!
