### ISSUE TITLE
FileLoadException

### ISSUE THREAD

**Issue by SamAchten** [dennisdoomen/fluentassertions#295]
When running tests for Windows Phone a FileLoadException is thrown. Visual Studio builds the project but crashes at runtime.
The error message is as follows:
Test Name:	FilterCalls
Test FullName: MobileVikings.VikingApp.Belgium.Test.Controller.UsageControllerTest.FilterCalls
Test Source:	C:\Users\jande\Documents\GitHubVisualStudio\viking-app-wp\MobileVikings.VikingApp\MobileVikings.VikingApp.Belgium.Test\Controller\UsageControllerTest.cs : line 39
Test Outcome:	Failed
Test Duration:	0:00:11.7792665

Result StackTrace:	at MobileVikings.VikingApp.Belgium.Test.Controller.UsageControllerTest.FilterCalls()
Result Message:	Test method MobileVikings.VikingApp.Belgium.Test.Controller.UsageControllerTest.FilterCalls threw exception: 
System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.0.20.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by dennisdoomen** [comment]
Thank you for reporting this. Which version of FA are you using?

**Comment by SamAchten** [comment]
The latest stable according to the NuGet package manager (4.0.0)

**Comment by SamAchten** [comment]
I downgraded to version 3.5 and it works now.

**Comment by dennisdoomen** [comment]
Hmm, version 4.0 only compiles in Visual Studio 2015, so I would not be surprised if it doesn't work. Which Windows Phone platform are you using?

**Comment by SamAchten** [comment]
I am using Visual Studio 2015, and building for windows phone 8.1.

**Comment by dennisdoomen** [comment]
@onovotny Does this ring a bell?

**Comment by JanJoris** [comment]
Any update on this one? The project is WP8.1 RT btw. Not SL.

**Comment by dennisdoomen** [comment]
I honestly have no clue. Trying to get some help [here](https://gitter.im/dennisdoomen/fluentassertions).

**Comment by dennisdoomen** [comment]
Is it possible to create a little project to reproduce this?

**Comment by dennisdoomen** [comment]
Should be fixed in 4.1
