### ISSUE TITLE
Error message building fails when reasonArgs contain "{" or "}"

### ISSUE THREAD

**Issue by tmenier** [dennisdoomen/fluentassertions#301]
It appears that you can't use the characters "{" or "}" in `reasonArgs` in the general `(..., because, reasonArgs)` assertion pattern. I suspect it should follow the same rules as `String.Format`, i.e. I need to take care to escape those characters in the `because` part, but not the `reasonArgs` part. Here's a simple demonstration of the failure:

    1.Should().Be(2, "can't use these in reasonArgs: {0} {1}", "{", "}");

The above is throwing a System.FormatException.

**Comment by dennisdoomen** [comment]
Duplicate of #287

**Comment by tmenier** [comment]
Thanks for reviewing. Duplicate in that the same fix will correct both? Symptom-wise this one's very different, primarily in that it's throwing a FormatException.

**Comment by dennisdoomen** [comment]
Different symptoms, same cause ;-)

**Comment by dennisdoomen** [comment]
Fixed in 4.0.1.
