### ISSUE TITLE
ExcludingNestedObjects issues

### ISSUE THREAD

**Issue by jannavarro** [dennisdoomen/fluentassertions#302]
I am having the same problem as logged by this guy on [SO](http://stackoverflow.com/questions/29677495/fluentassertions-graph-comparison-excludingnestedobjects-ignored). Is this a known issue?

**Comment by dennisdoomen** [comment]
Something similar was fixed in #194. Which version do you use?

**Comment by dennisdoomen** [comment]
Is this issue still relevant? (Also check the continued discussion in the SO post).

**Comment by jannavarro** [comment]
I got it to work now.
