### ISSUE TITLE
Assertion shouldn't traverse class properties tree

### ISSUE THREAD

**Issue by kornelf** [dennisdoomen/FluentAssertions#308]
I try to use your framework to writing Selenium WebDriver tests. But whent fluentassetions try to return an assertion error, then it starts to traverse all pageobject tree(15 levels down!), and it get a few hours to complete that single assert. Moreover if I have a list with 100000 elements, it will write it all! it's useless.

In my properties are many long time process references, so I don't want to traverse object tree for error message, because there is no data for that or it takes to long.

In confoguration there is no option to remove Formatter object and repleace with my own, so I can't override this setting.

Propositions to resolve problem:
1. Global configuration to just write type name or single ToString method(without traverse object)
2. Formaters list should be full public

Example to show the problem:
```
    public class Test
    {
        [Fact]
        public void DoTest()
        {
            List<A> listOfC = new List<A>();

            for (int i = 0; i < 10000000; i++)
            {
                listOfC.Add(new A() { Prop1 = "test" });
            }

            listOfC.Should().HaveCount(x => x < 0, "message"); //it will be freezed for cuple hours
        }

        class A
        {

            private string prop1;

            public string Prop1
            {
                get
                {
                    Thread.Sleep(40*1000); //delay, for example - http connection with 40s timeout
                    //throw new Exception("It shouldn't get here!");  //also it can throw exceptions, and I know that, so I don't want to assert get here
                    return prop1;
                }

                set
                {
                    prop1 = value;
                }
            }
        }
    }
```

**Comment by dennisdoomen** [comment]
Check the [Extensions](https://github.com/dennisdoomen/fluentassertions/wiki#extensibility-1). You have a few options.

**Comment by pveller** [comment]
@dennisdoomen, do you think this is a sensible default:

>> If a class doesn’t override ToString(), the built-in DefaultValueFormatter will render an object graph of that object

I wonder if the opposite makes more sense. Call `ToString()` (overridden or not) by default and allow to use an annotation if/when one needs/wants deep traversed formatting. I am currently experiencing the same issue and I have no control over `ToString()` in the objects I am inspecting in my tests. I don't believe I had the issue with v3. Only started experiencing timeouts when upgraded to v4 so I assume this was a relatively recent change, wasn't it?

**Comment by dennisdoomen** [comment]
Be it as it may, the ability of dumping the object's graph as part of an assertion failure has been one of the strongest pros of Fluent Assertions for years. And we did not change anything related to that. However, we did fix some problems in the object equivalency assertions not traversing some of the properties somewhere in the 3.1-3.6 range.

**Comment by mdilovar** [comment]
Would be nice to have a configurable timeout for such traversing.
