### ISSUE TITLE
Can ShouldBeEquivalentTo mutch by lambda?

### ISSUE THREAD

**Issue by TerraVenil** [dennisdoomen/fluentassertions#312]
public class Failure
    {
        public string Code { get; set; }
        public IEnumerable<string> ErrorMessages { get; set; }
    }

    var expectedCodes = new[] { "123", "456", "789" };
    var expectedErrorMessages = new[] { "Required" };
    
    var failures = new List<Failure>	{
    new Failure { Code = "123", ErrorMessages = new List<string> { "Required" } },
    new Failure { Code = "123", ErrorMessages = new List<string> { "Required" } }};
Can I do with ShouldBeEquivalentTo similar to pseudo code?

    failures.ShouldBeEquivalentTo(x => expectedCodes.Any(x.Code) && x.ErrorMessages.ContainInOrder(expectedErrorMessages));
Because right now I can do that with custom extension method.

**Comment by dennisdoomen** [comment]
No, you can't do that. Instead, you could create another `List<Failure>` that contains the data as you expect them, and pass that to `ShouldBeEquivalentTo` using option `WithStrictOrdering`.

**Comment by dennisdoomen** [comment]
@TerraVenil does this answer your question?

**Comment by TerraVenil** [comment]
Yes, please close this issue.
