### ISSUE TITLE
Custom assertions for objects containing collections

### ISSUE THREAD

**Issue by Meir017** [dennisdoomen/fluentassertions#313]
I'm trying to create a custom assertion for a custom type that looks something like this:
````csharp
public class ComplexObject
{
    public string[] Descriptions { get; }
    public double Size { get; }
}
````

I created a assertion class by extending ````ReferenceTypeAssertions<T>```` and added a function ````HaveSize(double size)```` to it.
I didn't find a way to add a function ````ContainDescriptions(IEnumerable<string> descriptions)```` and have it print my own fail message since it's implementation is ````Subject.Descriptions.Should().Contain(descriptions)````

**Comment by dennisdoomen** [comment]
That's a limitating of the C# compiler. As soon as I would define a generic `Should<T>(T type)`, it would override all the other existing methods on the [AssertionExtensions](https://github.com/dennisdoomen/fluentassertions/blob/master/Src/Shared/AssertionExtensions.cs) class

**Comment by Meir017** [comment]
What if the methods for asserting collection will be moved to a new class so we will be able to use them from custom assertion classes? then the collection assertions classes will call these methods

**Comment by dennisdoomen** [comment]
Are you referring to the methods of the `CollectionAssertions` class (and it's derivatives)?

**Comment by Meir017** [comment]
exactly

**Comment by dennisdoomen** [comment]
But you can already use that class directly.

**Comment by Meir017** [comment]
If I were to use the ````CollectionAssertions```` methods I wouldn't be able to use custom fail error.
In the example above I would like the error message to be something like ````Expected descriptions to contain {0}{reason}.

I way to implement this might be by deriving from the ````CollectionAssertions```` class and overriding the property ````Context```` to be descriptions

**Comment by tfsbuild** [comment]
You could wrap the call to `CollectionAssertions` in an `AssertionScope` and set the context explicitly. A bit like the [EquivalencyValidator](https://github.com/dennisdoomen/fluentassertions/blob/master/Src/Core/Equivalency/EquivalencyValidator.cs#L45) is doing.

**Comment by Meir017** [comment]
awsome, thanks :+1:
