### ISSUE TITLE
NCrunch support?

### ISSUE THREAD

**Issue by IngoBleile** [dennisdoomen/fluentassertions#314]
Hi team,

have you got an idea why NCrunch is ignoring code lines with .Should()...?

Thanks, Ingo

**Comment by dennisdoomen** [comment]
What do you mean with that? We use NCrunch quite heavily with XUnit

**Comment by IngoBleile** [comment]
Hi Dennis,

thanks for your fast answer! In lines where the Should extensions are used, e. g.

firstName.Should().Be('Ingo');

there are no black/red/green NCrunch dots on the left while all other lines are "dotted" like usual. But now, on my PC at home, everything is working fine, that's weird. OK - I'll have a look at it tomorrow in the office again and let you know then.

Thanks!
Ingo

**Comment by IngoBleile** [comment]
Hi Dennis,

my NCrunch was out of sync, that caused the problem, sorry! Everything is working fine.

Cheers
Ingo
