### ISSUE TITLE
support for comparing date only

### ISSUE THREAD

**Issue by lukefan6** [dennisdoomen/fluentassertions#319]
Something like DateTime.Now.Should().BeSameDateAs(DateTime.Today)

The closest workaround I can get is

DateTime expectedDate = DateTime.Today;
DateTime.Now.Should().HaveYear(expectedDate.Year)
                .And.HaveMonth(expectedDate.Month)
                .And.HaveDay(expectedDate.Day);

**Comment by dennisdoomen** [comment]
I would welcome a PR for this ;-)
