### ISSUE TITLE
Bug in EventRecordersMap.cs

### ISSUE THREAD

**Issue by Akuzo** [dennisdoomen/fluentassertions#320]
While Unittesting with XUnit, some tests failed, because EnventRecordersMap is not thread safe.
Also this issue just apear as we run the tests within the Test Explorer of Visual Studio 2013. 
NCrunsh shows all tests as passed.

Can somebody confirm that?

Thanks and regards,
Akuzo

**Comment by frankebersoll** [comment]
Confirmed and reproduced in https://github.com/dennisdoomen/fluentassertions/pull/321.
