### ISSUE TITLE
FailWithIncorrectConfiguration in UWP app after updating NuGet package to 4.1.0

### ISSUE THREAD

**Issue by NameOfTheDragon** [dennisdoomen/fluentassertions#322]
Having just updated my NuGet dependency for FluentAssertions from 4.0.1 to 4.1.0, I'm getting:
<pre>
System.InvalidOperationException

Failed to detect the test framework. Make sure that the framework assembly is copied into the test run directory

   at FluentAssertions.Execution.TestFrameworkProvider.FailWithIncorrectConfiguration()
</pre>

For what it's worth, I'm using XUnit for Devices in a UWP app, and it was working until I just updated the NuGet package - but why are you even looking at the unit test framework? I know assertions and unit tests often go hand-in-hand, but that's not _necessarily_ the case, surely? There's always going to be one you don't know about... so at the very least I would have thought you'd have some default rather than just falling over.

I've double checked, and the project builds and passes all tests with NuGet package 4.0.1 installed. Update to 4.1.0, and I get the exception again.

It's this project if you want to try to reproduce it: https://bitbucket.org/tigra-astronomy/ta.uwp.devices

**Comment by dennisdoomen** [comment]
Thanks for reporting this. I'll investigate, but I suspect it's looking for one of the supported framework so that it can throw the right type of exception. There is a bug in the NuGet resolution scheme that 4.0.1 was suffering from that caused it to use the wrong version of FA in UWP apps. That was fixed in 4.1.

**Comment by dennisdoomen** [comment]
@NameOfTheDragon how do I run the xUnit tests? The R# xUnit extension is not picking them up.

**Comment by NameOfTheDragon** [comment]
All can tell you is that, with no other changes, things break with either 4.1.0 (or, just verified, 4.1.1) where it fails to detect the test framework. If I downgrade to 4.0.1, it detects the very same framework fine and everything works again. It isn't a showstopper because I can just stay on 4.0.1 for now, but...

I'm using R# 10 and it is picking up the tests fine for me in the both runners (the normal one and the new "continuous testing session" runner). I think you have to install runner support in the R# Extension manager for it to detect xUnit tests. Looking an my R# extensions, I have `xUnit.net Test Support for ReSharper 10` installed.

However, failing that, you should be able to just RUN the test project - it is an executable. xUnit for devices is designed that way so you can run it on the target device (I have been able to run them on a Raspberry Pi 2 using that technique). The unit test app is, in effect, its own test runner. However it is very basic and doesn't provide much in the way of reporting, really just a red/green indication.

As a minimum, if you can't detect the test framework, please define and throw your own custom exception by default. I don't care (and the test framework shouldn't really care) what exact exception is thrown. I suppose that if you can use the 'right' exception and it provides some extra metadata or something, then that's good, but I think there should be a solid default action to fall back to if you can't detect the framework, rather than falling over.

**Comment by dennisdoomen** [comment]
Thanks for the explanation. Seems I didn't look well enough. Will keep you posted.

**Comment by dennisdoomen** [comment]
Fixed in 4.2.1
