### ISSUE TITLE
FluentAssertions missing from .NET OSS project list

### ISSUE THREAD

**Issue by tiesmaster** [dennisdoomen/fluentassertions#326]
Looking through [.NET Open Source Developer Projects](https://github.com/Microsoft/dotnet/blob/master/dotnet-developer-projects.md), I noticed that FluentAssertions was missing from the list (as I'm a big fan of this lib, and we're using it at work ;))

Guessing that you guys weren't aware of that list, maybe consider adding it there. I'm happy to put in a PR, but didn't want to do it without consulting ;)

**Comment by dennisdoomen** [comment]
Thanks for the tip! I've submitted a PR for this.
