### ISSUE TITLE
Edge case with ShouldBeEquivalentTo, Including() and similar property names

### ISSUE THREAD

**Issue by heemskerkerik** [dennisdoomen/fluentassertions#329]
Failing test here: https://gist.github.com/heemskerkerik/ab0531f45bf61f97fd14

Basically, I'm using `ShouldBeEquivalentTo()` with `Including()` to explicitly include a property to be matched, in this example called `DeclaredType`. The match fails on a different property, `Type`. When I rename `Type` to something like `InheritedType` (a remnant from trying to repro this issue), it succeeds.

Observed in 4.0 and 4.1.1.

**Comment by dennisdoomen** [comment]
Found the problem. The `IncludeMemberByPathSelectionRule` is comparing the properties using a `string.Contains` construct. Will ship a new release after I've fixed it.
