### ISSUE TITLE
Compile FluentAssertions on Windows 7, VS 2015

### ISSUE THREAD

**Issue by shift-evgeny** [dennisdoomen/FluentAssertions#336]
I tried to compile the latest source code using Visual Studio 2015 on Windows 7 x64 and got thousands of errors from the Core.Dotnet project, like this:

```
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(3,12,3,27): error CS0246: The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(4,12,4,29): error CS0246: The type or namespace name 'AssemblyCopyright' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(5,12,5,29): error CS0246: The type or namespace name 'AssemblyTrademark' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(6,12,6,27): error CS0246: The type or namespace name 'AssemblyCulture' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(7,12,7,27): error CS0246: The type or namespace name 'AssemblyVersion' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(8,12,8,31): error CS0246: The type or namespace name 'AssemblyFileVersion' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\SolutionInfo.cs(9,12,9,40): error CS0246: The type or namespace name 'AssemblyInformationalVersion' could not be found (are you missing a using directive or an assembly reference?)
1>C:\G it\fluentassertions\Src\FluentAssertions.Core.Dotnet\Properties\AssemblyInfo.cs(6,12,6,25): error CS0246: The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)
...
```

I know the website lists Windows 8.1 as a requirement, but is there any way to compile on Windows 7? I don't care about Windows Phone, Silverlight, etc. I just want a binary that I can run and debug on my system to troubleshoot another problem.

**Comment by dennisdoomen** [comment]
You need at least the Universal Windows Platform tools.

**Comment by shift-evgeny** [comment]
I think I have that installed:

![image](https://cloud.githubusercontent.com/assets/14869282/12169564/aa0a6952-b539-11e5-91f8-1ec4736aeb03.png)

and VS gives me the option of creating projects like "Blank App (Universal Windows)", "Class Library (Universal Windows)", etc. But building Core.Dotnet still fails. I've tried it from MSBuild (log attached), but didn't see any more helpful errors than from the VS UI.
[msbuild-out.zip](https://github.com/dennisdoomen/fluentassertions/files/81055/msbuild-out.zip)

**Comment by shift-evgeny** [comment]
OK, I managed to build it by removing the "ASP.NET Core 5" target from Core.Dotnet and Dotnet projects. That was by pure guesswork, though. It would be nice to give a more helpful error message in such cases.

I also had to fix the path to Microsoft.VisualStudio.TestPlatform.UnitTestFramework.dll in Portable.Specs to get that to compile, even though the "using" statements for it should have been excluded by the "#if !OLD_MSTEST".

**Comment by dennisdoomen** [comment]
@onovotny After all these months, I'm still confused on what is needed to compile Fluent Assertions. Do you have better insights on that? I thought Visual Studio 2015 with the UWP dev tools (as checked in the picture above) would be enough...

**Comment by onovotny** [comment]
So much stuff is in-flight.... VS 2015 Update 1 with the latest UWP tools at a minimum. There's a possibility the ASPNet 5 RC1 Update 1 tools are required too, but I'm not sure :/

Not sure about the OS requirement either as the dotnet projects aren't UWP, they're ".net core"/modern PCL.

**Comment by dennisdoomen** [comment]
I was afraid of that answer.....

**Comment by dennisdoomen** [comment]
Closing this issue.
