### ISSUE TITLE
Equivalency Comparison Behavior documentation

### ISSUE THREAD

**Issue by vgaltes** [dennisdoomen/fluentassertions#345]
Hi,

I think the example code of the Equivalency Comparison Behavior part of the documentation is incorrect. Instead of 

```
orderDto.ShouldBeEquivalentTo(order, options => options
    .Using<DateTime>(ctx => ctx.Date.Should().BeCloseTo(ctx.Date, 1000))
    .When(info => info.SelectedMemberPath.EndsWith("Date")));
```
should be
```
orderDto.ShouldBeEquivalentTo(order, options => options
    .Using<DateTime>(ctx => ctx.Subject.Should().BeCloseTo(ctx.Expectation, 1000))
    .When(info => info.SelectedMemberPath.EndsWith("Date")));
```

Thanks

**Comment by dennisdoomen** [comment]
You're correct.

**Comment by vgaltes** [comment]
Do you want me to create a pull request?

Sent from Outlook Mobile




On Fri, Jan 15, 2016 at 5:58 AM -0800, "Dennis Doomen" <notifications@github.com> wrote:












You're correct.

**Comment by dennisdoomen** [comment]
I think you can change the documentation directly

**Comment by vgaltes** [comment]
It seems that leo-ridgewood overtook me :-) Thanks!
