### ISSUE TITLE
Extension methods conflicting with 'humanizer' project

### ISSUE THREAD

**Issue by fedjabosnic** [dennisdoomen/FluentAssertions#352]
There seems to be a conflict for a number of your extension methods with ones from the **Humanizer library** (https://github.com/Humanizr/Humanizer).

For example:
- FluentAssertions.TimeSpanConversionExtensions.*
- Humanizer.NumberToTimeSpanExtensions.*

Both extension methods are in **root namespaces**, so the only solution seems to be to call the extension methods as static methods but that kind of defeats the purpose. Any chance of moving these utility type extensions to lower level namespaces so they have to be brought in directly with `using FluentAsssertions.Xxx;` or something similar - or perhaps you guys can collaborate on a smarter solution. 

Being able to use both libraries together would be ideal

Related issue: https://github.com/Humanizr/Humanizer/issues/524

**Comment by abatishchev** [comment]
This would be not just a braking change but a huge one and completely unnecessary. Just call as a static method.

You can sweeten this workaround by leveraging namespace alias, or static class alias introduced in C# 6.0

**Comment by dennisdoomen** [comment]
Agreed.
