### ISSUE TITLE
Comparing DateTimes doesn't appear to work as intended

### ISSUE THREAD

**Issue by sds88** [dennisdoomen/FluentAssertions#359]
I'm comparing two DateTimeOffsets, and FluentAssertions does not seem to be able to tell that they are in fact equal.

When using `dateTimeA.Should().Be(dateTimeB)` I got the following failure message:

> FluentAssertions.Execution.AssertionFailedException : Expected date and time to be <2016-03-02 18:11:27.827>, but found <2016-03-02 18:11:27.827>.

Those look the exact same to me, but I noticed there was a "close enough" method, so I tried that instead with `dateTimeA.Should().BeCloseTo(dateTimeB, precision: 100)`.  That also failed with a similar message:

>FluentAssertions.Execution.AssertionFailedException : Expected date and time to be within 100 ms from <2016-03-02 18:21:09.930>, but found <2016-03-02 18:21:09.930>.

**Comment by dennisdoomen** [comment]
Thanks for reporting. Do they have the same offset?

**Comment by sds88** [comment]
They don't have equal offsets, though the local times seem that they should still add up with the different offsets. I'm guessing that's what is causing them to not be equal?  It looks like this may have actually been an issue with us converting datetimes in the database we're using incorrectly instead of fluent assertions.

**Comment by dennisdoomen** [comment]
Yep. Although I do think that FA should include the offset in the failure message.

**Comment by dennisdoomen** [comment]
Ensured that the offset is included if it's non-zero.
