### ISSUE TITLE
support for NotBeOfType

### ISSUE THREAD

**Issue by SurajGupta** [dennisdoomen/FluentAssertions#366]
This is request for adding the assertion NotBeOfType, just the negation of BeOfType

**Comment by dennisdoomen** [comment]
Sure. I'd welcome a pull request if you will ;-)

**Comment by somewhatabstract** [comment]
https://github.com/dennisdoomen/FluentAssertions/pull/413

**Comment by snboisen** [comment]
Shouldn't this be closed with the merge of #413 ?

**Comment by dennisdoomen** [comment]
@snboisen  You're right
