### ISSUE TITLE
Collection assertions for ContainInOrder and Count without using both?

### ISSUE THREAD

**Issue by SurajGupta** [dennisdoomen/FluentAssertions#368]
I'd like to assert that one collection has all the same values in the same order as another collection.  It seems I can do that using `HaveCount().And.ContainInOrder()`.  Is there a more concise way to do that?  If not, I'd like to make a feature request for that - I think it would be a useful addition to the grammar.

**Comment by dennisdoomen** [comment]
Why don't you use `collection.Should().Equal(otherCollection)`?

**Comment by SurajGupta** [comment]
Yes!  completed missed that.

**Comment by dennisdoomen** [comment]
No problem. Happy to help.

Notice that there's also a [StackOverflow](http://stackoverflow.com/questions/tagged/fluent-assertions) tag for questions like these.
