### ISSUE TITLE
Add Json support

### ISSUE THREAD

**Issue by mkoertgen** [dennisdoomen/FluentAssertions#369]
Moving code https://github.com/awesome-inc/FluentAssertions.Json

**Comment by mkoertgen** [comment]
I'm on it.

**Comment by dennisdoomen** [comment]
:clap:

**Comment by mkoertgen** [comment]
Well, i added code, tests & packaging to the repo, cf.: 

https://github.com/awesome-inc/FluentAssertions/tree/fabf71143fea62da18058f603a7e437ce3fa6606

Right now, it's only the net45 package, so projects for other platforms should probably be added.
@dennisdoomen: Do you have an idea how to prioritize the platforms? Do we know how many users (=downloads) there are for the separate platforms, e.g. silverlight? Should we support all of them?

Aside from that, there is one thing i am not quite happy & sure about and which makes me hesitate to open a pull request: 

It's having 2 packages clinging to the same version. We are utilizing gitversion to work out the semantic version. And this is fine for one repo - one package. 

This means, fixing bugs in either package always requires a full release of all packages. I'm not sure if this works out well in the life cycle. My experience makes me wanting to avoid this.

One could argue that right now, fluentassertions is already divided into 2 packages (core + full). So this might a minor issue.

What are your opinions?

**Comment by mkoertgen** [comment]
Ok, i think odds are against merging the json code into the main repo. I will close the issue then.

**Comment by dennisdoomen** [comment]
Why? You were on the right track?

**Comment by mkoertgen** [comment]
Ah ok. Please share your opinion to me about platform prioritization, i.e. which platforms should be supported? 

But more importantly, what do you think about tying versions? Personally, i would try to avoid this. But my personal experience maybe biased.

**Comment by dennisdoomen** [comment]
You're concerns are valid. But if I look at how XUnit is doing it, it seems to be fine to release them together under the same version. IMO, the only reason why we would like to keep separate assemblies is to give people a choice to use the JSon assembly (and its associated dependencies). I'm already directly releasing every merge to *master*. Soon, I'll automate that so that every tag on *master* ends up on NuGet soon.

**Comment by dennisdoomen** [comment]
> Please share your opinion to me about platform prioritization, i.e. which platforms should be supported?

If possible, all. Not sure if JSON.NET supports all of them as well. Maybe it's enough to create equivalent assemblies for `Core.DotNet` and `Core.Pcl`.

**Comment by mkoertgen** [comment]
Ok thanks. That's what i needed.

**Comment by mkoertgen** [comment]
Added equivalent for `Core.Pcl` as `Json.Portable` in https://github.com/awesome-inc/FluentAssertions/commit/577f9cc9c4ee0fc7825203b03a354e80f107fa5c

**Comment by mkoertgen** [comment]
Added equivalent for `Core.Dotnet` as `Json.Dotnet` in https://github.com/awesome-inc/FluentAssertions/commit/2b25c966c13eb11dbe7aaeec9638662569948de7

**Comment by mkoertgen** [comment]
Opened PR https://github.com/dennisdoomen/FluentAssertions/pull/375

**Comment by mkoertgen** [comment]
Continued in PR #391

**Comment by dennisdoomen** [comment]
Part of release [4.6.0](https://github.com/dennisdoomen/FluentAssertions/releases/tag/4.6.0)

**Comment by dennisdoomen** [comment]
@mkoertgen It seems I can't push my Jason package since you already own that package on NuGet.

**Comment by mkoertgen** [comment]
@dennisdoomen Just added you as package owner. Please retry

**Comment by dennisdoomen** [comment]
Can I just overwrite your package?

**Comment by mkoertgen** [comment]
Sure.

**Comment by dennisdoomen** [comment]
What's your Twitter handle?

**Comment by mkoertgen** [comment]
@mkoertg
