### ISSUE TITLE
Permanently exclude properties/fields

### ISSUE THREAD

**Issue by samiraguiar** [dennisdoomen/FluentAssertions#371]
A lot of our classes derive from a base class which has a DateTime property. This property almost always makes the tests fail because of milliseconds difference. The thing is that it shouldn't even be compared since it's automatically initialized, so we always have to manually use the Excluding method to skip it. Is there a way to exclude it from all the assertions? Any attribute maybe?

**Comment by dennisdoomen** [comment]
You can consider to set some global settings on the `AssertionOptions` class.

**Comment by samiraguiar** [comment]
Thanks a lot, @dennisdoomen, that did the trick.
