### ISSUE TITLE
xUnit 2 discovery fails if xunit.assert isn't loaded

### ISSUE THREAD

**Issue by randomizer101** [dennisdoomen/FluentAssertions#373]
`xunit.assert` isn't loaded until one of the `Assert.*` methods is called. If this doesn't happen before a test fails, an `AssertionFailedException` is thrown instead of an `XunitException`. If the framework is specified in the application config file then FluentAssertions throws an exception because it can't find the framework.

I've worked around this by explicitly loading the assembly in my top level test classes' static constructors, but I'd prefer not to have to remember this for every class. Is it possible to have FluentAssertions attempt to load the assembly itself before determining if the framework is available?

**Comment by dennisdoomen** [comment]
How could I force loading the assembly?

**Comment by randomizer101** [comment]
I am currently loading it by calling `Assembly.Load` with the assembly's simple name, rather than the full name. This means that there is no version or public key check. I'm not sure if this is appropriate in this case or if you'd want to use the full name instead. I suppose you could derive most of the full name from `xunit.core` which will already be loaded, but that would make an assumption that the versions of each assembly are kept in sync.

**Comment by dennisdoomen** [comment]
That's what FA is doing as well: https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Shared/Execution/LateBoundTestFramework.cs#L42

**Comment by randomizer101** [comment]
Only if running under CoreCLR. I am running this under CLR, so it just checks the assemblies currently in the AppDomain.

**Comment by dennisdoomen** [comment]
Yes, you're right. I think I should be able to fix that.
