### ISSUE TITLE
'ShouldBeEquivalentTo' strange behavior for nullable Enums

### ISSUE THREAD

**Issue by grieg** [dennisdoomen/FluentAssertions#388]
Currently 'ShouldBeEquivalentTo' assumes null value as equivalent of first value of Enum. I think this behavior is a  bug and should be corrected. Example:

        [Fact]
        public void ThisTestShouldFail()
        {
            MyEnum? value = null;
            value.ShouldBeEquivalentTo(MyEnum.Value1);
        }

        enum MyEnum
        {
            Value1,
            Value2,
        }

**Comment by dennisdoomen** [comment]
Fixed in 4.6.2
