### ISSUE TITLE
Visual Studio crashes when FA attempts to write large arrays

### ISSUE THREAD

**Issue by LukeDWood** [dennisdoomen/FluentAssertions#401]
I've currently got a test that checks an object for null that's in a failing state. FA helpfully prints the object to the test runner when a null check fails, including any properties, however this causes VS to crash with a generic message ("Microsoft Visual Studio has stopped working") when one of those properties is a large array.

This appears to be a memory issue as can be seen below (I was only running the one test).
![image](https://cloud.githubusercontent.com/assets/13216206/15141744/8197adb0-1699-11e6-9b4e-cc92a4184570.png)

The array being printed is a byte array with a size of 21,353,878 and my computer has 12GB of RAM if this helps.

**Comment by dennisdoomen** [comment]
Thanks for reporting. Is it a byte[]?

**Comment by LukeDWood** [comment]
Yes, it's a byte[]
