### ISSUE TITLE
vstest.executionengine.exe crashes on StackOverflow error when running lots of unit tests using fluent assertions

### ISSUE THREAD

**Issue by wmevius** [dennisdoomen/FluentAssertions#419]
Hi,

When executing 2000 unit tests occasionally vstest.executionengine.exe crashes with 0XC00000FD 'The thread used up its stack'.

Looking at the stack when this happens (through the dump), it looks like a fluent assertions issue. There are thousands of fluent assertion calls on the stack (see below for a sample).

Any idea what we're doing wrong?

Cheers,
Willem

FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetPropertyValueTextFor(object value, System.Reflection.PropertyInfo propertyInfo, int nextPropertyNestingLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetTypeAndPublicPropertyValues(object obj, int nestedPropertyLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.Formatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetPropertyValueTextFor(object value, System.Reflection.PropertyInfo propertyInfo, int nextPropertyNestingLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetTypeAndPublicPropertyValues(object obj, int nestedPropertyLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.Formatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetPropertyValueTextFor(object value, System.Reflection.PropertyInfo propertyInfo, int nextPropertyNestingLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetTypeAndPublicPropertyValues(object obj, int nestedPropertyLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.Formatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetPropertyValueTextFor(object value, System.Reflection.PropertyInfo propertyInfo, int nextPropertyNestingLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.GetTypeAndPublicPropertyValues(object obj, int nestedPropertyLevel, System.Collections.Generic.IList<object> processedObjects)
FluentAssertions.dll!FluentAssertions.Formatting.DefaultValueFormatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)
FluentAssertions.dll!FluentAssertions.Formatting.Formatter.ToString(object value, bool useLineBreaks, System.Collections.Generic.IList<object> processedObjects, int nestedPropertyLevel)

**Comment by dennisdoomen** [comment]
Thanks for reporting this. What version of FA are you using?

**Comment by wmevius** [comment]
2.1 - would upgrading help?

**Comment by dennisdoomen** [comment]
Well, I do recognize a problem like that, so changes are that it is fixed later on. Your version is almost three years old.

**Comment by wmevius** [comment]
Well you know how it is, big organizations are reluctant to make changes that could impact everything. Would upgrading to 2.2 be the safest bet? Or do you suggest going to 3.0?

**Comment by dennisdoomen** [comment]
Which .NET version are you using?

**Comment by wmevius** [comment]
.Net 4.5. I found that some people are using 3.3 in our organization already, so it should be relatively painless (as in from a bureaucracy point of view) to upgrade to that.

**Comment by dennisdoomen** [comment]
Then I would highly recommend to upgrade to 4.x. I only support 3.0 for critical issues.

**Comment by dennisdoomen** [comment]
Assuming that 4.x fixes this.

**Comment by wmevius** [comment]
It does. Thanks! :)

Sent from my Windows Phone
________________________________
