### ISSUE TITLE
How to exclude Ids for ShouldBeEquivalentTo?

### ISSUE THREAD

**Issue by FilipFilipov** [dennisdoomen/FluentAssertions#424]
I know you can do `Excluding(ctx => ctx.SelectedMemberPath.Equals("Id"))`, but that will not work on nested objects or arrays. Using `.EndsWith("Id")` instead will work, but will also exclude any foreign keys that by convention end in "Id". Is there a way to exclude a property with an exact name, no mater where in the hierarchy it is?

**Comment by dennisdoomen** [comment]
What about including a bit more of the path? E.g. like `].SomeProperty.Id`?

**Comment by FilipFilipov** [comment]
A combination of `.Equals("Id")` and `.EndsWith(".Id")` as default rules works for my purposes. I only really needed to handle top level array members, because I have another rule to exclude nested objects, since they don't play well with entity framework's lazy loading.
