### ISSUE TITLE
Implement ShouldAllBeOfType() and ShouldAllBeOfExactType for enumerables

### ISSUE THREAD

**Issue by jon-armen** [dennisdoomen/FluentAssertions#428]
Say I have an instance of AggregateException.  I want to say aggEx.InnerExceptions.ShouldAllBeOfExactType<MyException>().  This would ensure that all objects in the collection are exactly MyException, and not derived.  I could also use the ShouldAllBeOfType to allow for derived classes.  Attempting to keep this request in line with how actions use ShouldThrow or ShouldThrowExactly.

**Comment by dennisdoomen** [comment]
So using exceptions here is just an example?

**Comment by jon-armen** [comment]
Right, another example might be if I have a collection such as List<object>, IEnumerable<IInterface>, or IList<BaseType>.  For any of these, It would be nice to say ShouldAllBeOfType.

**Comment by dennisdoomen** [comment]
Released in 4.18.0
