### ISSUE TITLE
Fluent Assertions for .Net Core

### ISSUE THREAD

**Issue by phding** [dennisdoomen/FluentAssertions#430]
I am a big fan of fluent assertions. As .Net Core 1.0.0 release, does Fluent Assertions has any plan to support .Net Core?

**Comment by dennisdoomen** [comment]
It already does.

**Comment by phding** [comment]
My fault, I didn't notice that. Thanks for response!

**Comment by dennisdoomen** [comment]
No worries. I had to verify it myself.

**Comment by amruthbinish** [comment]
I have the plan to migrate projects ((Framework 4.6.2 ) to .NET core. The existing project we are using FluentAssertions  , Version=4.19.2.0 . Can any one answer ,Is FluentAssertions   support ,NET Core ? if yes which Version of .NET Core version (Core 1.0 and 2.0) ? and which .NET Standard version it's support? Thanks

**Comment by dennisdoomen** [comment]
It currently supports .NET Core (through .NET Standard 1.3)

**Comment by amruthbinish** [comment]
Thanks . One more question Does .NET Core (through .NET Standard 1.3) support  "FluentAssertions.Core, Version=4.19.2.0" and "FluentAssertions , Version=4.19.2.0" as well ?

**Comment by amruthbinish** [comment]
Thank you !!

**Comment by amruthbinish** [comment]
Hope both "FluentAssertions.Core, Version=4.19.2.0" and "FluentAssertions , Version=4.19.2.0" support .NET Core (through .NET Standard 1.3). Thansk

**Comment by dennisdoomen** [comment]
Yep. It does.
