### ISSUE TITLE
.Should().Equal(...) enumerates the collection multiple times

### ISSUE THREAD

**Issue by thomaslevesque** [dennisdoomen/FluentAssertions#437]
Similar to #124 

I tried to upgrade the tests of my [Linq.Extras](https://github.com/thomaslevesque/Linq.Extras) library to the latest version of FluentAssertions, and suddenly many tests started breaking. Apparently a change introduced in 4.3.0 caused FA to enumerate the collection multiple times. Since I wrap my collections specifically to ensure that they're enumerated only once (see #124 for details), the tests break...

**Comment by dennisdoomen** [comment]
Aich. Do you know which extension method is the cause of this?

**Comment by thomaslevesque** [comment]
@dennisdoomen I'm not sure what you mean...

It happens for instance in [this test](https://github.com/thomaslevesque/Linq.Extras/blob/8f142089b92b34bad203355455c4c6100bda11d9/Linq.Extras.Tests/XEnumerableTests/CommonPrefixTests.cs#L36):

        [Test]
        public void CommonPrefix_Returns_Common_Prefix_Of_Two_Sequences()
        {
            var source = new[] { 4, 8, 15, 16, 23, 42 }.ForbidMultipleEnumeration();
            var other = new[] { 4, 8, 15, 99, 123, 999 }.ForbidMultipleEnumeration();
            var result = source.CommonPrefix(other);
            result.Should().Equal(4, 8, 15);
        }

**Comment by dennisdoomen** [comment]
Ah, `Should().Equal()`. That was my question ;-)

**Comment by thomaslevesque** [comment]
The workaround is easy, I just need to call `ToList()` on the result to materialize it. But I think it would be better for FA to enumerate only once, if it's possible.

**Comment by dennisdoomen** [comment]
Agreed
