### ISSUE TITLE
Problems with detached entitities in Entity Framework

### ISSUE THREAD

**Issue by asdftyp** [dennisdoomen/FluentAssertions#441]
It seems that `context.MyEntity.Should().HaveCount(1)` have the side effect to attach the entities. While `context.MyEntity.Count().Should.Be(1)` does not. 

It seems for me not to be consistent behavior which should be fixed. The expected behavior was *not* to attach the entities.

 Code example:

    [TestMethod]
    public void CheckFluentAssertions()
    {
      
      using (var context = MyContext())
      {
        var stateMgr = ((IObjectContextAdapter)context).ObjectContext.ObjectStateManager;
        var entity = new MyEntity { SomeValue = 123 };

        // Add
        context.MyEntities.Add(entity);
        context.SaveChanges();

        // Detach
        context.Entry(entity).State = EntityState.Detached;

        System.Console.WriteLine("Count: {0}", stateMgr.GetObjectStateEntries(EntityState.Unchanged).Count());
        // output is: 0

        context.MyEntities.Count().Should().Be(1);

        System.Console.WriteLine("Count: {0}", stateMgr.GetObjectStateEntries(EntityState.Unchanged).Count());
        // output is: 0

        context.MyEntities.Should().HaveCount(1);

        System.Console.WriteLine("Count: {0}", stateMgr.GetObjectStateEntries(EntityState.Unchanged).Count());
        // output is: 1
      }
    }

Maybe its not a bug which should be fixed, but I have spend couple of days to realize one error in my code.

My FluentAssertions version is 4.11.0. Entity Framework v6.1.3

**Comment by dennisdoomen** [comment]
What do you mean with "attach an entity"?

**Comment by asdftyp** [comment]
By attaching an entity to a context, they are tracked. (https://msdn.microsoft.com/en-us/data/jj592676.aspx).

This happens e.g. if one adds an entity to the context, as in the example by `Context.MyEntities.Add(entity);`. 

Detaching happens by `Context.Entry(entity).State = EntityState.Detached;`

The notion is actually problematic if one works with ASP.NET services then one receives a copy of the object which is not known to the context. Hence by adding it to the context it treats the entity as a new one, even it has an existing primary key.

**Comment by dennisdoomen** [comment]
Ah, that kind of attaching. The problem you're observing is the lazy-loading behavior that EF exposes. For FA to be able to count your objects, it has to enumerate the `context.MyEntities` collection. There's nothing I can do about that. That's the way EF (and NHibernate) work.
