### ISSUE TITLE
InvalidCastException when using NotBeOfType<T>

### ISSUE THREAD

**Issue by snboisen** [dennisdoomen/FluentAssertions#443]
There is a copy/paste bug in the implementation of the generic NotBeOfType assertion in ReferenceTypeAssertions: when the method attempts to create the return value, it casts Subject to the type we have just asserted it NOT to be.
Instead the method signature should be changed, so the return type is AndConstraint and then no casts are needed.
See my code comment in PR #413 for details.

**Comment by somewhatabstract** [comment]
Great catch, @snboisen. This should have a test too just to make sure it doesn't get reintroduced. Thanks!

**Comment by dennisdoomen** [comment]
Released through 4.13

**Comment by MattConroy** [comment]
Looks like this has been reintroduced. I'm using 4.7.0 and I have the same issue. The decompiler tells me that NotBeOfType is casting the type to T that it should not be again.

**Comment by dennisdoomen** [comment]
4.7?

**Comment by MattConroy** [comment]
Haha, apologies. I thought 4.7.0 was the latest. Just updated to 5.6.0 and it's fine!
