### ISSUE TITLE
The .dll download link on the website points to an old version

### ISSUE THREAD

**Issue by stijnherreman** [dennisdoomen/FluentAssertions#454]
The .dll download link on the website points to v3.1.229 while the current version is 4.13.0
Can you update it to point to the latest version?

(Normally I'd just use NuGet, but I'm working on a project where NuGet is not allowed.)

**Comment by dennisdoomen** [comment]
Fixed!

**Comment by dennisdoomen** [comment]
Oh, and thanks for reporting :+1:

**Comment by vossad01** [comment]
Assuming it gets merged, I have removed these download links from the website.

When plain DLLs are needed they can still be acquired via NuGet.  A .nupkg is just a zip file containing certain files and it is easy to extract DLLs from it.  [The nupkg can be downloaded NuGet.org without needing to use any NuGet client.](http://stackoverflow.com/a/32681762/1072626)
