### ISSUE TITLE
ICloneable2

### ISSUE THREAD

**Issue by flubbes** [dennisdoomen/FluentAssertions#455]
Is the interface ICloneable2 meant to be public? Even if it is meant to be public, could someone explain its usefulness to me?

[Screenshot](http://shnig.de/ZFoWAR)

**Comment by dennisdoomen** [comment]
No, it is not. Somehow, I never noticed.

**Comment by dennisdoomen** [comment]
Does that answer your question?

**Comment by flubbes** [comment]
It answers my question. Thanks.
