### ISSUE TITLE
Is it possible to set default DateTimeKind when using builder

### ISSUE THREAD

**Issue by garethbudden** [dennisdoomen/FluentAssertions#461]
The date time builder is a very useful little extension class - in our code however we use UTC everywhere, but the builder always returns a DateTime object with it's kind set to Unspecified.

Is it possible to tell the builder to create DateTime's as UTC by default instead. and if not would you accept a pull request for this?

**Comment by dennisdoomen** [comment]
How would you make the distinction between normal dates and times and the UTC ones?

**Comment by garethbudden** [comment]
DateTime has a property named Kind who's value is DateTimeKind.  It can be set in the datetime ctor I think. Or is that not what you meant?

**Comment by dennisdoomen** [comment]
No, I meant to ask what the API would look like.

**Comment by garethbudden** [comment]
Ah I see yes that makes more sense!
I'd not really got much further than posing the question really - essentially I'd like to be able to do the following and have it generate a DateTime as UTC
```c#
17.August(2016)
```
at the moment we have to do 
```c#
17.August(2016).ToUniversalTime()
```
Could a configuration value be added to the AssertionOptions? Or even a static config property on the extension class?

**Comment by dennisdoomen** [comment]
No, static stuff should be avoided at all costs. So I don't see how we could support both, other than by using an extension method like you suggested.

**Comment by garethbudden** [comment]
The ```ToUniversalTime()``` is already available on DateTime - I'd just rather not have to remember to call it each time I use the extensions

**Comment by dennisdoomen** [comment]
I understand your pain, but maybe you should change your API to convert whatever is passed as a `DateTime` to UTC.

**Comment by garethbudden** [comment]
The problem is my models are using UTC, but the fluent builders have dates built as Unknown, so the following _example test_ fails
```c#
var user = repo.GetUser(1);
user.Date.Should().Be(17.August(2016).At(19, 45));
```

That's why I was wondering about adding something to AssertionOptions such as
```c#
AssertionOptions.AssertEquivalencyUsing(options => options.DateTimesAsUTC);
```
in a similar way that you have
```c#
AssertionOptions.AssertEquivalencyUsing(options => options.ComparingEnumsByValue);
```

**Comment by dennisdoomen** [comment]
I'm sorry, but I think this does not belong in FA. I think that the notion of whether something is UTC or not must be explicit. For instance, in our projects, we post-fix UTC-based date and time properties with `Utc`. So in your case, your assertion would look like this:

`user.DateUtc.Should().Be(17.August(2016).At(19, 45).InUniversalTime());`
