### ISSUE TITLE
.Should.Be() with uint? requires explicit cast

### ISSUE THREAD

**Issue by LukeDWood** [dennisdoomen/FluentAssertions#466]
Calling `.Should.Be()` on a nullable uint requires casting the expected value to uint?, otherwise you can get a confusing failure message such as
> Expected object to be 1, but found 1.

Example code:
> uint? nullableUintTest = 1;   
nullableUintTest.Should().Be(1);

Fixed by:
> uint? nullableUintTest = 1;   
nullableUintTest.Should().Be((uint?)1);

**Comment by LukeDWood** [comment]
Apologies, this appears to be a duplicate of #435

**Comment by dennisdoomen** [comment]
No problem.
