### ISSUE TITLE
ShouldBeEquivalentTo does not handle enum values > long.MaxValue

### ISSUE THREAD

**Issue by msackton** [dennisdoomen/FluentAssertions#467]
When using ShouldBeEquivalentTo, for example to compare to object graphs, the assertion fails if any enumeration has a value greater than long.MaxValue.

Failing test:

 public enum EnumBig : ulong
    {
        ValueOne = UInt64.MaxValue, 
        ValueTwo = Int64.MaxValue,
        ValueThree = 0
    }

        public void ShouldBeEquivalentTo_should_succeed_when_asserting_large_enum_equals_large_enum()
        {
            Action act = () => EnumBig.ValueOne.ShouldBeEquivalentTo(EnumBig.ValueOne);
            act.ShouldNotThrow();
        }

Changing the EnumEqualityStep.Handle method to use Convert.ToDecimal rather than Convert.ToInt64 will fix this.

I would create a PR but I'm not sure where to add the test.

Updated to add: Using options.ComparingEnumsByName() does work as expected here, so that is an easy workaround for my use case (I don't actually need to compare by value).

**Comment by dennisdoomen** [comment]
Fixed by PR #470
