### ISSUE TITLE
Error with List<> inside another List<>

### ISSUE THREAD

**Issue by ricsmania** [dennisdoomen/FluentAssertions#474]
When I have a List<> in my class, and I compare a list of this class I get a strange behavior.

The following code reproduces the problem (also available on [Fiddle](https://dotnetfiddle.net/MgKIvU)):

```C#
using System.Collections.Generic;
using FluentAssertions;

public class Program
{
	class MyClass
	{            
		public string TableName { get; set; }
		public List<string> Columns { get; set; }
	}

	public static void Main()
	{
		List<MyClass> result = new List<MyClass>()
		{
			new MyClass() {TableName = "FIRST_TABLE" },
				
			new MyClass() {
				TableName = "SECOND_TABLE",
				Columns = new List<string>() {}
			}
		};
		
		List<MyClass> expected = new List<MyClass>()
		{
			new MyClass() {TableName = "FIRST_TABLE_WITH_DIFFERENT_NAME" },
				
			new MyClass() {
				TableName = "SECOND_TABLE",
				Columns = new List<string>() {}
			}
		};
		result.ShouldBeEquivalentTo(expected);
	}
}
```

If I run this code I get the following error:

> Run-time exception (line 34): Expected item[0].TableName to be 
"FIRST_TABLE_WITH_DIFFERENT_NAME" with a length of 31, but 
"SECOND_TABLE" has a length of 12.
Expected item[0].TableName to be 
"FIRST_TABLE_WITH_DIFFERENT_NAME", but 
"SECOND_TABLE" differs near "SEC" (index 0).
Expected item[0].Columns to be <null>, but found {empty}.

As you can see the collection is inverted, comparing the first item to the second and vice-versa.

If I remove the Columns from both collections then it works correctly:

```C#
using System.Collections.Generic;
using FluentAssertions;

public class Program
{
	class MyClass
	{            
		public string TableName { get; set; }
		public List<string> Columns { get; set; }
	}

	public static void Main()
	{
		List<MyClass> result = new List<MyClass>()
		{
			new MyClass() {TableName = "FIRST_TABLE" },
				
			new MyClass() {
				TableName = "SECOND_TABLE",
				//Columns = new List<string>() {}
			}
		};
		
		List<MyClass> expected = new List<MyClass>()
		{
			new MyClass() {TableName = "FIRST_TABLE_WITH_DIFFERENT_NAME" },
				
			new MyClass() {
				TableName = "SECOND_TABLE",
				//Columns = new List<string>() {}
			}
		};
		result.ShouldBeEquivalentTo(expected);
	}
}
```

> Run-time exception (line 34): Expected item[0].TableName to be 
"FIRST_TABLE_WITH_DIFFERENT_NAME" with a length of 31, but 
"FIRST_TABLE" has a length of 11.

**Comment by dennisdoomen** [comment]
By default, it compares collections without caring about the order because it tries to compare collections for equivalence. If you care about the order, you can use the `UseStrictOrdering` option on the 2nd argument of `ShouldBeEquivalentTo`.

**Comment by ricsmania** [comment]
Hello @dennisdoomen 

I have tested the WithStrictOrdering option and it works as expected.

Thank you very much!
