### ISSUE TITLE
Equivalency.AssertIsCompatiblyTypedDictionary fails with NullReferenceException in case 'expectation' parameter is null

### ISSUE THREAD

**Issue by YuriGuzun** [dennisdoomen/FluentAssertions#479]
It fails at that line: https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Equivalency/GenericDictionaryEquivalencyStep.cs#L83

**Comment by dennisdoomen** [comment]
Thanks for reporting this.

**Comment by MaksimSimkin** [comment]
Should be fixed already with fix for https://github.com/dennisdoomen/FluentAssertions/issues/468

**Comment by dennisdoomen** [comment]
@YuriGuzun can you confirm that this is fixed by the latest FA version?

**Comment by YuriGuzun** [comment]
Yep it works as expected in 4.15.0. Thanks.
