### ISSUE TITLE
ExcludingNestedObjects does not work

### ISSUE THREAD

**Issue by billzhang3046** [dennisdoomen/FluentAssertions#480]
Hello,

I am using FluentAssertions 4.1.4 and found ExcludingNestedObjects are not working as expected. Below test method should be passed but actually it showed me below message. Do you have any idea? Thanks!

Best wishes,
Bill

> Expected member Home to be 

> UnitTestProject1.Address
{
   Street = "A"
}, but found &lt;null>.

> With configuration:
- Use declared types and members
- Compare enums by value
- Match member by name (or throw)
- Be strict about the order of items in byte arrays

```csharp
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void TestMethod1()
        {
            var personA = new Person { Name = "A" };
            var personB = new Person { Name = "A", Home = new Address { Street = "A" } };
            personA.ShouldBeEquivalentTo(personB, options => options.ExcludingNestedObjects());
        }
    }

    public class Person
    {
        public Address Home { get; set; }

        public string Name { get; set; }
    }

    public class Address
    {
        public string Street { get; set; }
    }
```

**Comment by dennisdoomen** [comment]
Thanks for reporting this. The purpose of `ExcludingNestedObjects` is to prevent FA from recursively comparing the properties of your `Address` class. Instead, it will do a simple `Equals` on the property value. In your case it means FA is comparing that instance of the `Address` class with `null`, which is the correct behavior here.

**Comment by billzhang3046** [comment]
Thanks for explanation! I think my question will be can FA perform any shallow comparison or FA compares objects deeply all the time?

Best wishes,
Bill

**Comment by dennisdoomen** [comment]
That specific problem was fixed. But my original explanation still stands.

**Comment by billzhang3046** [comment]
Understood. Thanks!
