### ISSUE TITLE
FluentAssertions missing from http://up-for-grabs.net/

### ISSUE THREAD

**Issue by tiesmaster** [dennisdoomen/FluentAssertions#481]
@dennisdoomen I was talking to you yesterday, and you suggested looking at some up-for-grabs issues. I didn't find anything interested yet, but I did notice that FA is not one of the projects shown on the "aggregation site" http://up-for-grabs.net/.

Shall I create a PR to add FA to it?

**Comment by dennisdoomen** [comment]
Cool. I didn't even know about that site. So, yes, by all means.

BTW, did you check https://github.com/dennisdoomen/FluentAssertions/issues?q=is%3Aissue+is%3Aopen+label%3A%22up+for+grabs%22?

**Comment by tiesmaster** [comment]
Yeah, indeed, I did notice that you're using the label, and looked through real quickly, but haven't found the time to look at them in more detail.

As you can, I've put in the PR to get it added to the up-for-grabs site. I've copied the description from what you added based on #326.

**Comment by tiesmaster** [comment]
And, it's done ;)
