### ISSUE TITLE
Extend SelfReferencingCollectionAssertions with HaveAny

### ISSUE THREAD

**Issue by nerumo** [dennisdoomen/FluentAssertions#494]
I'd like to write the statement
`projects.Should().HaveAny()`

Today I have to write 
`projects.Any().Should().BeTrue()`

**Comment by dennisdoomen** [comment]
What about `projects.Should().NotBeEmpty()`?

**Comment by nerumo** [comment]
there it is,  thank you



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Dennis Doomen <notifications@github.com>
Datum: 02.11.16 18:36 (GMT+01:00)
An: dennisdoomen/FluentAssertions <FluentAssertions@noreply.github.com>
Cc: Marco Bachmann <mb@triarc-labs.com>, Author <author@noreply.github.com>
Betreff: Re: [dennisdoomen/FluentAssertions] Extend SelfReferencingCollectionAssertions with HaveAny (#494)


What about projects.Should().NotBeEmpty()?

-
