### ISSUE TITLE
[Feature] Let ReSharper warn about 'Should()' without following assertion

### ISSUE THREAD

**Issue by ulrichb** [dennisdoomen/FluentAssertions#499]
The following sample test contains a test code bug, which isn't detected by the compiler, nor raises an error at run-time.

```C#
[Test]
public void MyTest()
{
    var result = CallSut();

    result.SomeProp.Should().Be("a");
    result.AnotherProp.Should(); // Missing assertion
}
```

For R# users, this could be solved by adding [`[MustUseReturnValue]` or `[Pure]`](https://www.jetbrains.com/help/resharper/2016.2/Reference__Code_Annotation_Attributes.html#MustUseReturnValueAttribute) to all the `Should()` extension method overloads.

This can be achieved by adding the necessary annotation attributes into the FluentAssertion library and making the types internal (e.g. like [EF Core](https://github.com/aspnet/EntityFramework/blob/fa0b7ec85f2a5323835c5940dbef7ddce8cdd098/src/Shared/CodeAnnotations.cs) does this). See [this blog entry](https://blog.jetbrains.com/dotnet/2015/08/12/how-to-use-jetbrains-annotations-to-improve-resharper-inspections/) for more information.

Would you accept a PR?

**Comment by dennisdoomen** [comment]
Absolutely!

**Comment by ulrichb** [comment]
OK. I can do this, but is one decision to take.

a) Use `System.Diagnostics.Contracts.Pure` ...
  * ➕ Is part of the BCL. Maybe other static analyzers could benefit from the attributes on the `Should()` methods.
  * ➖ Needs a `CONTRACTS_FULL` compilation symbol in all projects because the attribute is annotated with a `ConditionalAttribute`.
  * ➖ Requires a dependency to `System.Diagnostics.Contracts` in the .NET Core project, because it seems that this package is not part of `NETStandard.Library`.

b) Use `JetBrains.Annotations.Pure` ...
  * ➕ Can be included in the "Core" project (using the method described above) without additional dependencies / no compilation symbol required,
  * ➖ Is JetBains-specific.

I tend to option b) mainly because of the `System.Diagnostics.Contracts`-reference drawback.

**Comment by dennisdoomen** [comment]
I agree with option b).

**Comment by ulrichb** [comment]
=> 
![2016-11-08 22_37_42-externalannotationstestbench - microsoft visual studio](https://cloud.githubusercontent.com/assets/388796/20118223/0275bf86-a604-11e6-9a7d-ceb04e3685d7.png)
