### ISSUE TITLE
AssemblyAssertions Does Not Inherit From ReferenceTypeAssertions

### ISSUE THREAD

**Issue by JasonBock** [dennisdoomen/FluentAssertions#501]
Because this class doesn't inherit from `ReferenceTypeAssertions`, I can't use methods like `BeNull()`

**Comment by dennisdoomen** [comment]
You're right. Apparently we forgot about that. I'd welcome a PR if you want to fix this yourself.

**Comment by JasonBock** [comment]
To be more precise, I think it's more that `AssemblyAssertions` doesn't have a specific `Be()` method like `StringAssertions` does, but either way, yes, this should be fixed. And @dennisdoomen I'd love to fix it, but right now I'm fixing all my test code as I'm moving from NUnit to xUnit+FluentAssertions, so I have a bunch of code to update to get my tests running again :). But once I get that done I'll see if I can submit a PR for this.

**Comment by JasonBock** [comment]
As I fix my code I'm finding more....

`MethodInfoAssertions` is missing `Be()`

**Comment by dennisdoomen** [comment]
Released in 4.18
