### ISSUE TITLE
MonitorEvents called from multiple Tasks throws exception

### ISSUE THREAD

**Issue by informatorius** [dennisdoomen/FluentAssertions#505]
When I call MonitorEvents() on multiple objects from multiple Tasks then I get this exception:

> System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length. at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary2.CopyTo(KeyValuePair2[] array, Int32 index) at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable1 source)
> at FluentAssertions.Events.EventRecordersMap.ForEach(Object eventSource, Action1 action) at FluentAssertions.Events.EventRecordersMap.Add(Object eventSource, IEnumerable1 recorders)
> at System.Threading.Tasks.Task.Execute()

Looks like the problem is in class EventMonitor with the eventSource being a WeakReference.
When I replace the WeakReference by an Object then the issue does not occur.
```

    [TestClass]
    public class MonitorEventsCalledFromMultipleTasks
    {
        class ClassUnderTest
        {
            public event EventHandler event1;
        }

        [TestMethod]
        public void Loop()
        {
            var tasks = new List<Task>();
            for (int i = 0; i < 100; i++)
            {
                tasks.Add(Task.Run(() =>
                {
                    var step = new ClassUnderTest();
                    
                    step.MonitorEvents();
                }));
            }
            Task.WaitAll(tasks.ToArray());
        }
    }
```

UseCase is e.g. parallel unit test execution where each unit test calls MonitorEvents() on its class under test.

**Comment by informatorius** [comment]
I found a solution, do you like it?
D:\GitHub\FluentAssertions\Src\Shared\Events\EventMonitor.cs
```
private void EnsureEventHandlerAttached(EventInfo eventInfo)
        {
            IEventRecorder recorder;
            if (!registeredRecorders.TryGetValue(eventInfo.Name, out recorder))
            {
                **var target = eventSource.Target;**
                recorder = new EventRecorder(**target**, eventInfo.Name);
                registeredRecorders.Add(eventInfo.Name, recorder);
                var handler = EventHandlerFactory.GenerateHandler(eventInfo.EventHandlerType, recorder);
                eventInfo.AddEventHandler(**target**, handler);
            }
        }
```

**Comment by dennisdoomen** [comment]
Unfortunately it will cause a memory leak since the targets will never get released by the GC.

**Comment by informatorius** [comment]
Why targets do not get released? It is still a weak reference.

**Comment by dennisdoomen** [comment]
You're correct, but you're effectively creating new records on the fly. So with that you're ignoring the fact this API simply doesn't work with *async*/*await* where the contexts jumps from one thread to the other. As long as that `[ThreadStatic]` is there, you can't fix that.

**Comment by informatorius** [comment]
There is no async/await in my example.

**Comment by dennisdoomen** [comment]
I know, but the overall culprit here is the ThreadStatic.
