### ISSUE TITLE
Should().Be Infinite recursion {Maximum recursion depth was reached...}

### ISSUE THREAD

**Issue by mzanin** [dennisdoomen/FluentAssertions#509]
This example causes the test to fail due to an infinite recursion issue in FluentAssertions.
```

using FluentAssertions;
using NUnit.Framework;

namespace Test
{
    class Foo
    {
        public Foo KillerProperty
        {
            get { return new Foo(); }
        }
    }

    [TestFixture]
    public class TestFailure
    {
        [Test]
        public void ThisTestCrashes()
        {
            var foo1 = new Foo();
            var foo2 = new Foo();

            foo1.Should().Be(foo2);
        }
    }
}
```

with an output of: 

```
Expected object to be 

Rsm.Test.Foo
{
   KillerProperty = Test.Foo
   {
      KillerProperty = Test.Foo
      {
         KillerProperty = Test.Foo
         {
            KillerProperty = Test.Foo
            {
               KillerProperty = Test.Foo
               {
                    KillerProperty = {Maximum recursion depth was reached...}
...
```

**Comment by dennisdoomen** [comment]
Thanks for reporting this. Looking at your example code, I clearly see a recursion issue. How would you expect FA to handle this situation?

**Comment by mzanin** [comment]
I was using an older version of FluentAssertions which caused the vstest.execution engine to crash when this test was run. The latest FluentAssertions does not cause a crash but simply fails the test, so this is already an improvement. 
I might be way off track here but it looks like the issue is in the code which generates the string output for the operation. One way to solve it would be to detect when a property creates such a recursive case and simply stop evaluating that property.

**Comment by dennisdoomen** [comment]
Yeah, but in this case the recursion is caused by you creating an undetectable infinite loop.

**Comment by mzanin** [comment]
It's not such an unlikely scenario though, there are many cases where a property might create an instance of the class it belongs to.  You could create a heuristic to determine whether a property can potentially cause an infinite object graph by looking at the IL code of the property. Another way would be to track the max depth of a property which has a return type of it's parent, or something along those lines...

**Comment by dennisdoomen** [comment]
Sorry, but in this case I'm convinced FA is doing the right thing. You cannot expect the library to go that far.
