### ISSUE TITLE
How to chain multiple 'And' when checking exception with FluentAssertions

### ISSUE THREAD

**Issue by mabead** [dennisdoomen/FluentAssertions#510]
_I wasn't able to have an answer on [StackOverflow](http://stackoverflow.com/questions/40592015/how-to-chain-multiple-and-when-checking-exception-with-fluentassertions) so I post the question directly on the FluentAssertions forum..._

I have a unit test that validates that some code throws an exception and that two properties have the expected value. Here is how I do it:
```
var exception = target.Invoking(t => t.CallSomethingThatThrows())
    .ShouldThrow<WebServiceException>()
    .And;

exception.StatusCode.Should().Be(400);
exception.ErrorMessage.Should().Be("Bla bla...");
```

I don't like the look of the assertion that must be done in three statements. Is there an elegant way to do it in a single statement? My first intuition was to use something like this:

```
target.Invoking(t => t.CallSomethingThatThrows())
      .ShouldThrow<WebServiceException>()
      .And.StatusCode.Should().Be(400)
      .And.ErrorMessage.Should().Be("Bla bla...");
```
Unfortunately, this doesn't compile. Any idea on how to do it?

**Comment by dennisdoomen** [comment]
You can do something like:

target.Invoking(t => t.CallSomethingThatThrows())
      .ShouldThrow<WebServiceException>()
      .Where(e => e.StatusCode == 400)
      .Where(e => e.ErrorMessage == "Bla bla...");

**Comment by mabead** [comment]
Looks good to me. Thanks!
