### ISSUE TITLE
Infinite loop when calling xxx.Should().BeNull()

### ISSUE THREAD

**Issue by flodpanter** [dennisdoomen/FluentAssertions#519]
Hi there. I am testing a domain-model which in some cases contains bidirectional relations. For instance I have a class A that has a property that returns class B. B has a property that returns type A.

This seems to be causing an infinite loop within the Fluentassertion code. 

Dump from debugging:
![image](https://cloud.githubusercontent.com/assets/3274517/21079690/d533a75e-bf99-11e6-84e3-8f87000ab9ec.png)

Is there any way around this?

**Comment by dennisdoomen** [comment]
Thank you for reporting this. Which version are you using? I'm pretty sure the formatter limits the amount of recurstion

**Comment by flodpanter** [comment]
I upgraded to 4.17.0 as I read about similar issues had been resolved in this version. This did not have any effect. You mention that the formatter has a recursion limit, but this does not seem to fix the underlying problem. Also, I am surprised that the BeNull() method needs to run through all properties. I dont see the need for this. Is there any specific reason?

**Comment by IharBury** [comment]
> Is there any specific reason?

When the assertion fails, the method throws an exception and the message contains the value which was expected to be null (but was not). When the value is a custom object, it's formatted including all its property values.

**Comment by flodpanter** [comment]
I am aware that this it what actually happens, but this does not answer why this is the case. I would expect the IsNull-method to only tell me if the object is null or not. Should I want details about properties, I would use a different method such as the ShouldBeEquivalentTo-method. I would expect this method to compare all properties of my class, hence I would also expect it to write out any properties that are not equivalent.

It is a matter of what to expect and obviously this is just my opinion. I would expect the actual assertions and the formatting of any error message to always use the same algorithm. 

My expectation:
if( a!=null)  return "a is not null"

Current impl (which to me is not logical):
if(a!=null) run through all properties of and display details of these.

**Comment by dennisdoomen** [comment]
This is on purpose. It should normally help you stay out of the debugger. Don't you want to know the value of the object if it is not `null`?

**Comment by flodpanter** [comment]
No I do not. If I want detailed information, I would call a different method such as ShouldBeEquivalentTo. In my opinion, the method does to much which causes unexpected side effects such as the one that inspired this thread. I use the Fluentassertion framework for both pure unit tests and for db integration/io/service tests. By calling the BeNull-method, I could potentially trigger calls to these resources. That is another reason why it should be very clear, what side effects the different methods have. 

Maybe there is a case here for customizing the error message provider :-) In other words, if you disagree twith me, and still think that the BeNull-method should check all properties, is there room for this kind of extensibility of the framework? I have missed it before as the error messages tend to "explode" into very long hard-to-read strings and I find myself spending some time trying to find the one property that is not equivalent.

**Comment by dennisdoomen** [comment]
You can override some of the formatting behavior. Read [this section](https://github.com/dennisdoomen/fluentassertions/wiki#extensibility-1) to learn more about that.

**Comment by flodpanter** [comment]
What is your advice regarding the infinite loop?

**Comment by dennisdoomen** [comment]
It should stop recursing until 10 levels deep (or something).

**Comment by flodpanter** [comment]
Is it possible to set customize the recursion limit?

**Comment by dennisdoomen** [comment]
Nope. See https://github.com/dennisdoomen/FluentAssertions/blob/master/Src/Core/Formatting/Formatter.cs#L76
