### ISSUE TITLE
DeepEqual

### ISSUE THREAD

**Issue by benoj** [dennisdoomen/fluentassertions#86]
Hi,

Love this package BTW. 

When writing my unit tests I had some value objects which i wanted to compare. In node's chai package this is very simple (deep equal). With the current implementation of fluent assertions there isn't a very nice way to do this. 

However when i combined with this package https://github.com/jamesfoster/DeepEqual then i could suddenly say:

object1.ShouldDeepEqual(object2);

I think this is a far superior way than is currently available in fluent assertions and maybe you should bring this feature in?

**Comment by dennisdoomen** [comment]
No response in almost a year's time. Closing it now.
